project:
  type: website
  preview:
    port: 4200
  post-render: 
    - scripts/post-render.py

bibliography: references.bib
cap-location: margin

website:
  title: "Mingze Gao"
  favicon: images/favicon.png
  twitter-card: true
  site-url: https://mingze-gao.com
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: research/index.md
        text: Research
      - href: posts/index.qmd
        text: Blog
  page-footer: 
    left: "Copyright © 2019 - 2024 Mingze Gao" 
    right: 
      - icon: github
        href: https://github.com/mgao6767
      - icon: twitter 
        href: https://twitter.com/AdrianMingzeGao
      - icon: linkedin
        href: https://www.linkedin.com/in/adriangao/
      - icon: send
        href: mailto:mingze.gao@mq.edu.au
  sidebar:
    title: Teaching
    contents:
      - section: "Fixed Income"
        contents:
          - posts/fixed-income/introduction/index.qmd
          - posts/fixed-income/bond-prices-and-yields/index.qmd
          - posts/fixed-income/bond-price-volatility/index.qmd
          - posts/fixed-income/yield-curve/index.qmd
      - section: "Stata Workshop"
        contents:
          - posts/stata/introduction/index.qmd
          - posts/stata/packages/index.qmd
          - posts/stata/working-with-datasets/index.qmd
          - posts/fred/index.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mermaid:
      theme: default
