project:
  type: website
  preview:
    port: 4200

bibliography: references.bib
cap-location: margin

website:
  title: "Mingze Gao"
  favicon: images/favicon.png
  twitter-card: true
  site-url: https://mingze-gao.com
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: research.md
        text: Research
      - href: posts.qmd
        text: Blog
  page-footer: 
    left: "Copyright © 2019 - 2024 Mingze Gao" 
    right: 
      - icon: github
        href: https://github.com/mgao6767
      - icon: twitter 
        href: https://twitter.com/AdrianMingzeGao
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


