project:
  type: website
  preview:
    port: 4200
  post-render: 
    - scripts/post-render.py

highlight-style: github
code-block-bg: true

bibliography: references.bib
cap-location: margin

language: 
  search-box-placeholder: Search

website:
  title: "Mingze Gao"
  favicon: images/favicon.png
  twitter-card: true
  site-url: https://mingze-gao.com
  google-analytics: "G-1QDTTQ6EHM"
  back-to-top-navigation: true
  search:
    type: textbox
  navbar:
    logo: images/favicon.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: research/index.md
        text: Research
      - href: posts/index.qmd
        text: Blog
  page-footer: 
    left: "Copyright © 2019 - 2024 Mingze Gao" 
    right: 
      - icon: github
        href: https://github.com/mgao6767
      - icon: twitter 
        href: https://twitter.com/AdrianMingzeGao
      - icon: linkedin
        href: https://www.linkedin.com/in/adriangao/
      - icon: send
        href: mailto:mingze.gao@mq.edu.au
  sidebar:
    title: Teaching
    contents:
      - section: "Fixed Income"
        contents:
          - posts/fixed-income/introduction/index.qmd
          - posts/fixed-income/bond-prices-and-yields/index.qmd
          - posts/fixed-income/bond-price-volatility/index.qmd
          - posts/fixed-income/yield-curve/index.qmd
      - section: "Stata Workshop"
        contents:
          - posts/stata/introduction/index.qmd
          - posts/stata/packages/index.qmd
          - posts/stata/working-with-datasets/index.qmd
          - posts/fred/index.md

format:
  html:
    theme:
      - cosmo
      - styles.scss
    css: styles.css
    toc: true
    mermaid:
      theme: default
    code-copy: true
    syntax-definitions: 
      - syntax/sas.xml
