# Project information
site_name: Mingze Gao
site_description: A Random Walk Away Finance.
site_author: Mingze Gao
site_url: https://mingze-gao.com

# Repository
# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: Copyright &copy; 2018 - 2021 Mingze Gao

# Configuration
theme:
  name: material
  features:
    - tabs
  language: en
  palette:
    primary: white
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: favicon.ico
  logo: favicon.png
  custom_dir: overrides

# Extras
extra:
  disqus: mingze-gao
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mgao6767
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/adriangao

# Google Analytics
google_analytics:
  - UA-114057186-1
  - auto

# Plugins
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  # - codehilite:
  #     linenums: true
  #     guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra_javascript:
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

nav:
  - Home: index.md
  - CV: cv.md
  - Data: data/index.md
  - Specurve: specurve/index.md
  - Research Notes:
    - "Decomposing Herfindahl–Hirschman (HHI) Index": posts/decomposing-hhi-index/index.md
    - "What it takes to be a CEO? A fun survey of literature": posts/what-it-takes-to-be-a-ceo/index.md
    - "Bank holding companies' financials from FR Y-9C": posts/get-bank-holding-company-financials/index.md
    - "Compute jackknife coefficient estimates in SAS": posts/compute-jackknife-coefficient-estimates-in-sas/index.md
    - "Compute weekly return from daily CRSP data": posts/compute-weekly-return-from-daily-crsp-data/index.md
    - "Convert between numeric and character variables": posts/convert-between-numeric-and-character-variables/index.md
    - "Encode password for SAS remote submission": posts/encode-password-for-sas-remote-submission/index.md
    - "Firm Historical Headquarter State from SEC 10K/Q Filings": posts/firm-historical-headquarter-state-from-10k/index.md
    - "Generate Fama-French industry classification from SIC": posts/generate-fama-french-industry-classification-from-sic/index.md
    - "Identify Chinese State-Owned Enterprise using CSMAR": posts/identify-chinese-state-owned-enterprise-using-csmar/index.md
    - "Merge Compustat and CRSP": posts/merge-compustat-and-crsp/index.md
    - "Texutal analysis on SEC filings": posts/textual-analysis-on-sec-filings/index.md
    - "Use SAS macros on WRDS": posts/use-sas-macros-on-wrds/index.md
    - "Winsorization in SAS": posts/winsorization-in-sas/index.md
  - Teaching Notes:
    - "Beta, unlevered and levered": posts/beta-unlevered-and-levered/index.md
    - "Call option value from two approaches": posts/call-option-value-from-two-approaches/index.md
    - "Minimum variance hedge ratio": posts/minimum-variance-hedge-ratio/index.md
    - "Reconciliation of Black-Scholes variants": posts/reconciliation-of-black-scholes-variants/index.md
  - Personal Blog:
    - "100 Bitcoins forgone for science": posts/100-bitcoins-forgone-for-science/index.md
    - "Accumulator option pricing": posts/accumulator-option-pricing/index.md
    - "Bitcoin address generator in obfuscated Python": posts/bitcoin-address-generator-in-obfuscated-python/index.md
    - "Bloomberg BQuant (BQNT)": posts/bloomberg-bquant/index.md
    - "LeGao to make your own LEGO mosaics": posts/legao-to-make-your-own-lego-mosaics/index.md
    - "Never use a brain wallet": posts/never-use-a-brain-wallet/index.md
    - "Python Shared Memory in Multiprocessing": posts/python-shared-memory-in-multiprocessing/index.md
    - "Setup Docker/Ngnix and Let's Encrypt on Ubuntu": posts/docker-nginx-letsencrypt/index.md
    - "Working remotely on a Windows Machine from VSCode on a Mac": posts/working-remotely-on-a-windows-machine-wsl-from-vscode-on-a-mac/index.md
  # - Interactive Option Pricing: /option-pricing-explained
  # - LeGao - Make LEGO Mosaics: /legao
  - Measures:
    - Overview: measures/measures.md
    - Firm Characteristics:
      - Accounting Restatement: measures/accounting_restatement.md
      - Asset Tangibility: measures/asset_tangibility.md
      - Book Leverage: measures/book_leverage.md
      - Capital Expenditure: measures/capital_expenditure.md
      - Credit Rating: measures/credit_rating.md
      - Executive Ownership: measures/executive_ownership.md
      - Firm Size: measures/firm_size.md
      - Market to Book: measures/market_to_book.md
      - ROA: measures/roa.md
      - ROE: measures/roe.md
      - Stock Delisting: measures/stock_delisting.md
      - Tobin's Q: measures/tobin_q.md
    - Bank Holding Company (BHC) Characteristics:
      - BHC Size: measures/bhc_size.md
      - BHC Loan Growth: measures/bhc_loan_growth.md
      - BHC FX Exposure: measures/bhc_fx_exposure.md
      - BHC NetIncome/Assets: measures/bhc_netincome_to_assets.md
      - BHC Dividend/Assets: measures/bhc_dividend_to_assets.md
      - BHC RegulatoryCapital/Assets: measures/bhc_regcap_to_assets.md
      - BHC Tier1Capital/Assets: measures/bhc_tier1cap_to_assets.md
      - BHC Gross IR Hedging: measures/bhc_gross_ir_hedging.md
      - BHC Gross FX Hedging: measures/bhc_gross_fx_hedging.md
      - BHC Maturity Gap: measures/bhc_maturity_gap.md
    - Market Microstructure:
      - "Kyle's Lambda": measures/kyleslambda.md
      - "Lo and MacKinlay (1988)": measures/lomackinlay1988.md
  - Timetable: timetable.md