site_name: Mingze Gao
site_description: Mingze Gao's personal website.
site_author: Mingze Gao
site_url: https://mingze-gao.com
# repo_url: https://github.com/mgao6767/mingze-gao.com
# repo_name: mgao6767/mingze-gao.com

copyright: Copyright &copy; 2019 - 2023 <a href="https://mingze-gao.com">Mingze Gao</a>

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

plugins:
  - include-markdown
  - search
  - charts:
      vega_theme: default
  - typeset
  - meta:
      meta_file: '**/.meta.yml'
  - blog:
      blog_dir: posts
      post_url_format: "{slug}"
      archive_toc: true
      categories_toc: true
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tags:
      tags_file: tags.md
  # - git-revision-date-localized:
  #     type: date
  #     enable_creation_date: true
  # - git-committers:
  #     repository: mgao6767/mingze-gao.com
  #     branch: master
  # - rss:
  #     match_path: posts/posts/.* 
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       - tags 
  - mkdocs-video:
      is_video: True
      video_loop: True
  - redirects:
      redirect_maps:
        curriculum-vitae/index.md: https://mingze-gao.com/cv/
        cv.md: https://mingze-gao.com/cv.pdf
        legao/index.md: https://mingze-gao.com/apps/legao/
        posts/merger_acquisition_deals_from_sdc_platinum.md: https://mingze-gao.com/posts/download-ma-deals-from-sdc-platinum/

theme:
  name: material
  favicon: favicon.ico
  logo: favicon.png
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    admonition:
      example: octicons/log-24
  features:
    - announce.dismiss
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - toc.follow 
    - navigation.prune 
    - navigation.tabs
    - navigation.path
    - navigation.indexes 
    - navigation.top

extra:  
  disqus: mingze-gao
  generator: false
  analytics:
    provider: google
    property: G-1QDTTQ6EHM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mgao6767/mingze-gao.com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/adriangao
    - icon: fontawesome/solid/paper-plane
      link: mailto:mingze.gao@sydney.edu.au

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - CV: cv.pdf
  - Research: research.md
  - Blog:
      - posts/index.md
      - Tags: tags.md
  # - About:
  #     - Me: about.md
  #     - Apps: apps.md
  - Readings:
      - Journals:
        - 2023: readings/journals/2023.md
        - 2022: readings/journals/2022.md
        - 2021: readings/journals/2021.md
        - 2020: readings/journals/2020.md
        - 2019: readings/journals/2019.md
        - 2018: readings/journals/2018.md
        - 2017: readings/journals/2017.md
        - 2016: readings/journals/2016.md
        - 2015: readings/journals/2015.md
        - 2014: readings/journals/2014.md
        - 2013: readings/journals/2013.md
        - 2012: readings/journals/2012.md
        - 2011: readings/journals/2011.md
        - 2010: readings/journals/2010.md
        - 2009: readings/journals/2009.md
        - 2008: readings/journals/2008.md
        - 2007: readings/journals/2007.md
        - 2006: readings/journals/2006.md
        - 2005: readings/journals/2005.md
        - 2004: readings/journals/2004.md
        - 2003: readings/journals/2003.md
        - 2002: readings/journals/2002.md
        - 2001: readings/journals/2001.md
        - 2000: readings/journals/2000.md
      - Nobel Laureates: readings/nobel-laureates.md
  - FINC50: 
      - finc50/index.md
      - Fixed Income: 
          - finc50/fixed-income/index.md
          - Introduction: finc50/fixed-income/introduction.md
          - Prices and Yields: finc50/fixed-income/bond-prices-and-yields.md
          - Price Volatility: finc50/fixed-income/bond-price-volatility.md
          - Yield Curve: finc50/fixed-income/yield-curve.md
      - Stata Workshop:
          - finc50/stata/index.md
          - Introduction: finc50/stata/introduction.md
          - Packages: finc50/stata/packages.md
          - Working with datasets: finc50/stata/working-with-datasets.md
          - FRED - Federal Reserve Economic Data: finc50/stata/fred.md
  - frds.io: https://frds.io