---
title: "AFIN8003 Week 12 - Loan Sales and Securitisation"
subtitle: "Banking and Financial Intermediation"
author: "Dr. Mingze Gao"
institute: "Department of Applied Finance"
date: 2024-10-23
draft: true
categories:
    - AFIN8003
    - 2024S2
format: 
  mq-revealjs: 
    chalkboard: true
    embed-resources: false
    echo: true
    code-fold: true
    footer: "AFIN8003 Banking and Financial Intermediation"
    mermaid-format: svg
  pdf:
    echo: false
    documentclass: article
    papersize: a4
    toc: true
    number-sections: true
    colorlinks: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fig-pos: "H"
    fig-width: 1
    fig-cap-location: "bottom"
    output-file: "Week12.pdf"
# Custom fields
pdf-name: "Week12.pdf"
---

# Loan Sales and Securitisation

## Introduction

- So far we have discussed many risks facing financial institutions, especially banks, and some of the many methods to manage them.
- This week, we discuss two more approaches:
    - loan sales
    - securitisation

- Loan sales involve a transfer of risk to buyers.
- Securitisation converts loans into tradable securities.
- They both enhance liquidity and provide funding for banks.
- The originate-to-distribute model:
    -  make loans
    -  loan sales and securitisation
    -  use proceeds to originate new loans/assets

# Loan sales

## Introduction

Central to bank risk management is credit risk, as discussed in [Week 6](https://mingze-gao.com/teaching/AFIN8003/2024S2/Week6) and [Week 8](https://mingze-gao.com/teaching/AFIN8003/2024S2/Week8).

Traditionally, banks adopt several mechanisms to manage credit risk:

1. charging higher interest rates and fees for loans extended to more risky borrowers
2. rationing credits (limit the amount) to more risky borrowers
3. requiring (more) collateral for loans to more risky borrowers
4. implementing more restrictive loan covenants
5. diversification
6. ...

In addition, FIs can use derivatives (e.g., forward, options, swaps) to manage their credit risk.

However, FIs now increasingly use loan sales and securitisation to control credit risk.

## Loan sales

- The use of credit derivatives allows an FI to reduce credit risk without removing assets from balance sheet.
- With loan sales, a loan is originated by an FI and then sold to an outside buyer (removed from the FI's balance sheet).
    - There is a transfer of _ownership_ from the seller to the buyer.
    - If a loan is sold without __recourse__, the FI has no explicit liability even if the loan defaults.
    - If a loan is sold with recourse, the buy may put the loan back to the selling FI under certain conditions.
    - In practice, most loans are sold without recourse.
- Loan sales do not create new types of securities such as the pass-throughs, CMOs, and MBBs, which are products of securitisation.


## Types of loan sales

::: {.columns}
:::: {.column}
__Traditional short-term loan sales__

- secured by assets of the borrowing firm.
- made to investment-grade borrowers or better.
- issued for a short term (90 days or less).
- have yields closely tied to the commercial paper rate.
- sold in units of $1 million and up.
::::
:::: {.column}
__Leveraged loan sales__

- term loans (TLs).
- secured by assets of the borrowing firm (usually given senior secured status).
- a long maturity (often three- to six-year maturities).
- have floating rates tied to LIBOR, the prime rate, or a CD rate.
- have strong covenant protection.

::: {.callout-note}
The definition of "leveraged loan" is ambiguous: some use spreads (e.g., +125bps) and others use rating criteria (e.g., BB- or lower).
:::

::: {.callout-note}
Leveraged loans can be:

- nondistressed (bid price exceeds 90 cents per $1 of loans), or 
- distressed (bid price is less than 90 cents per $1 of loans or the borrower is in default).
:::
::::
:::

## Types of loan sales contracts

Two basic forms by which loans can be transferred from seller to buyer.

::: {.columns}
:::: {.column}
__Participation__

- buyer is not a party to the underlying credit agreement so that the initial contract between loan seller and borrower remains in place after the sale.
- buyer can exercise only partial control over changes in the loan contract’s terms.
- buyer has a double risk exposure: underlying borrower and the selling FI.
::::
:::: {.column}
__Assignment__

- the most common type.
- all rights are transferred on sale, i.e. buyer holds a direct claim on the borrower.
- transfer of ownership
::::
:::

## The bank loan sales market

- @irani_rise_2021 provides a good summary.

- If you're interested in reading more, [check here](https://phds.io/papers/?all=%22secondary+loan+market%22).

## The buyers and sellers

::: {.columns}
:::: {.column}
__Buyers__

- Investment banks
- Vulture funds (a specialized fund that invests in distressed loans)
- Other domestic banks and foreign banks
- Insurance companies and pension funds
- Bank loan mutual funds
::::
:::: {.column}
__Sellers__

- Major money center banks
- Government and government agencies
- Investment banks
- Foreign banks
- _"Good bank-bad bank"_
    - Some special-purpose banks established to absorb distressed assets from "good" banks.
::::
:::

## Why loan sales?

Apart from credit risk management, there are some other reasons for FIs to sell loans.

1. Reserve requirements (becoming less important)
2. Fee income
3. Capital costs (by reducing risky assets)
4. Liquidity risk (by improving asset-side liquidity)

## Factors affecting loan sales growth

1. Access to the commercial paper market
2. Customer relationship
3. Legal concerns
4. BIS capital requirements
5. Market value accounting
6. Assert brokerage and loan trading
7. Government loan sales
8. Credit ratings
9. Purchase and sale of foreign bank loans
10. ...

# Securitisation

## Introduction

__Asset securitisation__ is another mechanism to manage credit risk, interest rate risk, liquidity and more.

- It is the process of packaging loans or other assets into newly created securities and selling these asset-backed securities (ABS) to investors.

## Mechanism


# Finally...

## Suggested readings

- [Loan Syndications and Trading Association (LSTA)](https://www.lsta.org/).
- Irani, R. M., Iyer, R., Meisenzahl, R. R., & Peydró, J.-L. (2021). [The Rise of Shadow Banking: Evidence from Capital Regulation](https://phds.io/papers/?title=The+Rise+of+Shadow+Banking:+Evidence+from+Capital+Regulation). _The Review of Financial Studies_, 34, 2181–2235..

## References
