---
title: Research
cap-location: margin
callout-appearance: minimal
---

## 👨‍💻 Data & Code

- (code) [Discretionary accruals](/posts/compute-jackknife-coefficient-estimates-in-sas)
- (code & data) [Historical firm HQ location 1969-2022](/posts/firm-historical-headquarter-state-from-10k)
- (code) [Merton distance-to-default (default probability)](/posts/merton-dd)
- (code) [Organization capital](/posts/estimate-organization-capital)
- (code) [Specification curve analysis](/posts/specification-curve-analysis) - listed in [Harvard Business School Research Computing Services blog](https://hbs-rcs.github.io/post/specification-curve-analysis/). For the Stata command, see my [`specurve`](https://github.com/mgao6767/specurve).
- (code) [Textual analysis on 8K filings](/posts/textual-analysis-on-sec-filings). For a full Python CLI application, see my [`edgar-analyzer`](https://github.com/mgao6767/edgar-analyzer).
- (code) [Variance ratio test - Lo and MacKinlay (1988)](/posts/lomackinlay1988)

## 📄 Publications

(@) [**Consumer Behaviour and Credit Supply: Evidence from an Australian FinTech Lender**](https://doi.org/10.1016/j.frl.2023.104205), with [Henry Leung](https://www.sydney.edu.au/business/about/our-people/academic-staff/henry-leung.html), Linhui Liu and [Buhui Qiu](https://sites.google.com/site/buhuiqiu/), ___Finance Research Letters___, 2023. [SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4505420)

    ::: {.callout-note collapse="false"}

    Consumer behaviour affects FinTech lending decisions.

    :::

(@) [**Closer Than Ever: Growing Business-level Connections Between Australia and Europe**](https://doi.org/10.1016/j.emj.2023.03.001), with Boris Choy, Teresa Davis, Hanyun Ding, Massimo Garbuio, Catherine Hardy, Henry Leung, Thanh Son Luong, Greg Patmore, Sandra Peter, Buhui Qiu, Kai Riemer, John Shields, Catherine Sutton-Brady, Carlos Vazquez-Hernandez, and Eliza Wu, ___European Management Journal___, 2023.

    ::: {.callout-note collapse="false"}

    - Invited submission

    :::

(@) [**Organization Capital and Executive Performance Incentives**](https://doi.org/10.1016/j.jbankfin.2020.106017), with [Henry Leung](https://www.sydney.edu.au/business/about/our-people/academic-staff/henry-leung.html) and [Buhui Qiu](https://sites.google.com/site/buhuiqiu/), ___Journal of Banking & Finance___, 2021. [SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3734710)

    ::: {.callout-note collapse="false"}

    A firm's organization capital has a substitution effect on its executive pay-for-performance sensitivity.

    - ___Outstanding PhD Student Paper Award___, 3rd Global PhD Colloquium.
    - FMA 2020, 3rd Global PhD Colloquium, 32nd Annual PhD Conference in Economics and Business.

    :::

## 📝 Working Papers

(@) **Anomalous Lending and Bank Risk**, with [Iftekhar Hasan](https://www.fordham.edu/gabelli-school-of-business/faculty/full-time-faculty/iftekhar-hasan/), [Buhui Qiu](https://sites.google.com/site/buhuiqiu/), [Eliza Wu](https://www.sydney.edu.au/business/about/our-people/academic-staff/eliza-wu.html) and [Yan Yu](https://business.uc.edu/faculty-research/obais/faculty/yan-yu.html).

    ::: {.callout-note collapse="false"}

    - _**Reject & Resubmit**_ at the _**Management Science**_.
    - MQBS Banking and Finance Forum 2024, FIRN 2023, Monash Winter Finance 2023, Machine Learning Methods for Business Workshop 2023,  BFBRG Workshop 2022, Deakin University, Loughborough University, University of Queensland, University of Sydney.

    :::

(@) [**Lone (Loan) Wolf Pack Risk**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4331418), with [Iftekhar Hasan](https://www.fordham.edu/gabelli-school-of-business/faculty/full-time-faculty/iftekhar-hasan/), [Buhui Qiu](https://sites.google.com/site/buhuiqiu/) and [Eliza Wu](https://www.sydney.edu.au/business/about/our-people/academic-staff/eliza-wu.html).

    ::: {.callout-note collapse="false"}

    - _**Reject & Resubmit**_ at the _**Contemporary Accounting Research**_.
    - WFA 2023, FIRN 2023, FIRN Banking 2022, Curtin University, Massey University, National Central University, University of Essex, University of Sydney.
    - ___The Brattle Group Best Paper Award___, FIRN 2023.
    - SUERF Policy Brief [No. 586](https://www.suerf.org/publications/suerf-policy-notes-and-briefs/the-big-problem-of-small-syndicates/), Bank of Finland Research Discussion Paper [No. 4/2023](https://ssrn.com/abstract=4391791).

    :::

(@) [**Borrower Technology Similarity and Bank Loan Contracting**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4579677), with Yunying Huang, [Steven Ongena](https://sites.google.com/site/stevenongena/) and [Eliza Wu](https://www.sydney.edu.au/business/about/our-people/academic-staff/eliza-wu.html).

    ::: {.callout-note collapse="false"}

    Banks accumulate technological expertise, beyond industry specialization, which reduces loan costs for borrowers whose technologies are familiar to the lenders.

    - SFS Cavalcade 2024, EFA 2023 (poster), FMA 2023, 35th AFBC, Macquarie University, University of Sydney.
    - Semifinalist for ___FMA 2023 Best Paper Award___.
    - CEPR Discussion Paper [DP18624](https://cepr.org/publications/dp18624).

    :::

(@) [**Catering to Environmental Premium in Green Venture Financing**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4522222), with [Henry Leung](https://www.sydney.edu.au/business/about/our-people/academic-staff/henry-leung.html), [Tse-Chun Lin](https://www.hkubs.hku.hk/people/tse-chun-lin/) and Tracy Thi Vu.

    ::: {.callout-note collapse="false"}

    Exactly when equity market is hyped about green firms, primary market investors' FOMO could ironically hurt early-stage green ventures.

    - Oxford Sustainable Private Markets Conference 2025, RBFC 2024, AsianFA 2024, Journal of Contemporary Accounting and Economics (JCAE) Annual Symposium 2024, 7th Advances in Venture Capital and Private Equity Research Workshop, National Taiwan University.
    - [Podcast](https://www.dropbox.com/scl/fi/zn2ahdzvyu4jg5gwr8kcu/Catering-to-Environmental-Premium-in-Green-Venture-Financing.wav?rlkey=p9lvr0xjomf8qbr737zy8mizd&st=05vizcv2&dl=0) by NotebookLM.

    :::

(@) [**When Everyone Agrees: How the 52 Week High Creates a Liquidity Barrier**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3925756), with [Joshua Della Vedova](https://sites.google.com/view/joshdellavedova/home), [Andrew Grant](https://www.sydney.edu.au/business/about/our-people/academic-staff/andrew-grant.html), [Joakim Westerholm](https://www.sydney.edu.au/business/about/our-people/academic-staff/joakim-westerholm.html) and [Barbara Bliss](https://www.sandiego.edu/business/about/biography.php?profile_id=1796).

    ::: {.callout-note collapse="false"}

    Investor consensus around 52 Week High creates a liquidity barrier - high liquidity does not necessarily improve market quality.

    - Previously titled as _Investor Disagreement, Liquidity and Informational Efficiency at the 52 Week High_.
    - FMA-Europe 2024, 17th International Behavioural Finance Conference, EFMA 2024, Multinational Finance Society annual meeting 2024, FMA 2020.

    :::

(@) **Real Estate Collateral, Lender Screening, and M&A Performance**, with Thanh Son Luong and [Buhui Qiu](https://sites.google.com/site/buhuiqiu/).

    ::: {.callout-note collapse="false"}

    - _**Revise & Resubmit**_ at the _**Journal of Corporate Finance**_.
    - FMA 2022, FIRN 2022.

    :::

(@) [**AI Adoption and Big Data in Supply Chains**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5039427), with [Giacinta Cestone](https://sites.google.com/view/giacintacestone/home), [Jiaying Li](https://sites.google.com/view/jiaying-li/home) and [Ruiqi Mao](https://www.ruiqi-mao.com/).

    ::: {.callout-note collapse="false"}

    - Nordic Initiative for Corporate Economics (NICE) 2025, 3rd Aarhus Workshop on Strategic Interaction in Corporate Finance, Macquarie University, NHH Norwegian School of Economics, University of Groningen.

    :::

(@) **Of Rivals and Role Models: The Impact of Foreign Bank Entry on Domestic Bank Opacity**, with [Guihua He](https://kjxy.zuel.edu.cn/2020/1118/c10624a256928/page.htm), [Weiping Li](https://fof.cityu.edu.mo/en/list-13/680), and Quan Yuan.

    ::: {.callout-note collapse="false"}

    Foreign bank entry into China reduces domestic bank opacity primarily through a learning channel than competitive pressure.

    :::

(@) [**Corporate Tax Reform and the Cost of Bank Loans: Evidence from the Tax Cuts and Jobs Act**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5396247), with Thanh Son Luong, [Buhui Qiu](https://sites.google.com/site/buhuiqiu/), Krishan Shankar, and [Eliza Wu](https://www.sydney.edu.au/business/about/our-people/academic-staff/eliza-wu.html). 

    ::: {.callout-note collapse="false"}

    The 2017 U.S. Tax Cuts and Jobs Act (TCJA) reduces bank loan costs for firms with greater foreign exposure, higher tax savings, and tighter ex ante financial constraints.

    :::

(@) **Earnings Downside Risk in Debt Contracting**, with [Steve Lim](https://www.neeley.tcu.edu/Lim,-Steve) and [Vassil Mihov](https://www.neeley.tcu.edu/Mihov-Vassil). 

## ‍🎓 Student Supervision

Students for whom I am the Associate Supervisor:

- Tracy Wu, MRes student at Macquarie University, 2024 (co-supervision with Elizabeth Sheedy).
- Meitong He, Honours student at University of Sydney, 2023 (co-supervision with Buhui Qiu). Graduated with First Class Honours.
