---
title: Teaching
author: ''
---

::: {.callout-note}
These materials are prepared for my teaching at the [Macquarie Business School](https://www.mq.edu.au/macquarie-business-school).

- The content may change before the actual delivery date to ensure the most up-to-date information is provided.
- These materials are intended solely for educational purposes within the scope of this course. Unauthorized use, distribution, or reproduction of any part of this material is prohibited.
- Additional resources and readings may be provided throughout the course to enhance learning experience.
- Please provide any suggestions for improvement, which will be considered for future revisions.
:::

<!-- ::: {#AFIN8003-2024S2}
::: -->


## Session 1, 2025

### AFIN8003 Banking and Financial Intermediation

| Date         | Lecture                                                                                                                                        | Workshop                                                                |
|--------------|------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------|
| Feb 27, 2025 | [Week 1 - Introduction](./AFIN8003/2025S1/Week1/index.qmd) ([PDF](./AFIN8003/2025S1/Week1/Week1.pdf))                                          | [Workshop 1](./AFIN8003/2025S1/Week1/workshop.qmd)                      |
| Mar 6, 2025  | [Week 2 - Risks and Regulation](./AFIN8003/2025S1/Week2/index.qmd) ([PDF](./AFIN8003/2025S1/Week2/Week2.pdf))                                  | [Workshop 2 (Jupyter Notebook)](./AFIN8003/2025S1/Week2/workshop.ipynb) |
| Mar 13, 2025 | [Week 3 - Capital Management and Adequacy](./AFIN8003/2025S1/Week3/index.qmd) ([PDF](./AFIN8003/2025S1/Week3/Week3.pdf))                       | [Workshop 3](./AFIN8003/2025S1/Week3/workshop.qmd)                      |
| Mar 20, 2025 | [Week 4 - Interest Rate Risk](./AFIN8003/2025S1/Week4/index.qmd) ([PDF](./AFIN8003/2025S1/Week4/Week4.pdf))                                    | [Workshop 4](./AFIN8003/2025S1/Week4/workshop.qmd)                      |
| Mar 27, 2025 | [Week 5 - Market Risk](./AFIN8003/2025S1/Week5/index.qmd) ([PDF](./AFIN8003/2025S1/Week5/Week5.pdf))                                           | [Workshop 5](./AFIN8003/2025S1/Week5/workshop.qmd)                      |
| Apr 3, 2025  | [Week 6 - Credit Risk I: Individual Loan Risk](./AFIN8003/2025S1/Week6/index.qmd) ([PDF](./AFIN8003/2025S1/Week6/Week6.pdf))                   |                                                                         |
| Apr 10, 2024 | [Week 7 - Credit Risk II: Loan Portfolio and Concentration Risk](./AFIN8003/2025S1/Week7/index.qmd) ([PDF](./AFIN8003/2025S1/Week7/Week7.pdf)) |                                                                         |

## Session 2, 2024

### AFIN8003 Banking and Financial Intermediation

| Date         | Lecture                                                                                                                                          | Workshop                                             |
|--------------|--------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------|
| Jul 24, 2024 | [Week 1 - Introduction](./AFIN8003/2024S2/Week1/index.qmd) ([PDF](./AFIN8003/2024S2/Week1/Week1.pdf))                                            | [Workshop 1](./AFIN8003/2024S2/Week1/workshop.qmd)   |
| Jul 31, 2024 | [Week 2 - Risks and Regulation](./AFIN8003/2024S2/Week2/index.qmd) ([PDF](./AFIN8003/2024S2/Week2/Week2.pdf))                                    | [Workshop 2](./AFIN8003/2024S2/Week2/workshop.qmd)   |
| Aug 7, 2024  | [Week 3 - Capital Management and Adequacy](./AFIN8003/2024S2/Week3/index.qmd) ([PDF](./AFIN8003/2024S2/Week3/Week3.pdf))                         | [Workshop 3](./AFIN8003/2024S2/Week3/workshop.qmd)   |
| Aug 14, 2024 | [Week 4 - Interest Rate Risk](./AFIN8003/2024S2/Week4/index.qmd) ([PDF](./AFIN8003/2024S2/Week4/Week4.pdf))                                      | [Workshop 4](./AFIN8003/2024S2/Week4/workshop.qmd)   |
| Aug 21, 2024 | [Week 5 - Market Risk](./AFIN8003/2024S2/Week5/index.qmd) ([PDF](./AFIN8003/2024S2/Week5/Week5.pdf))                                             | [Workshop 5](./AFIN8003/2024S2/Week5/workshop.qmd)   |
| Aug 28, 2024 | [Week 6 - Credit Risk I: Individual Loan Risk](./AFIN8003/2024S2/Week6/index.qmd) ([PDF](./AFIN8003/2024S2/Week6/Week6.pdf))                     | [Workshop 6](./AFIN8003/2024S2/Week6/workshop.qmd)   |
| Sep 4, 2024  | Week 7 - Midterm Exam                                                                                                                            | None                                                 |
| Sep 11, 2024 | [Week 8 - Credit Risk II: Loan Portfolio and Concentration Risk](./AFIN8003/2024S2/Week8/index.qmd) ([PDF](./AFIN8003/2024S2/Week8/Week8.pdf))   | [Workshop 8](./AFIN8003/2024S2/Week8/workshop.qmd)   |
| Oct 2, 2024  | [Week 9 - Liquidity Risk](./AFIN8003/2024S2/Week9/index.qmd) ([PDF](./AFIN8003/2024S2/Week9/Week9.pdf))                                          | [Workshop 9](./AFIN8003/2024S2/Week9/workshop.qmd)   |
| Oct 9, 2024  | [Week 10 - Liability and Liquidity Management](./AFIN8003/2024S2/Week10/index.qmd) ([PDF](./AFIN8003/2024S2/Week10/Week10.pdf))                  | [Workshop 10](./AFIN8003/2024S2/Week10/workshop.qmd) |
| Oct 16, 2024 | [Week 11 - Sovereign Risk, FX Risk, and Off-Balance-Sheet Risk](./AFIN8003/2024S2/Week11/index.qmd) ([PDF](./AFIN8003/2024S2/Week11/Week11.pdf)) | [Workshop 11](./AFIN8003/2024S2/Week11/workshop.qmd) |
| Oct 23, 2024 | [Week 12 - Loan Sales and Securitisation](./AFIN8003/2024S2/Week12/index.qmd) ([PDF](./AFIN8003/2024S2/Week12/Week12.pdf))                       | [Workshop 12](./AFIN8003/2024S2/Week12/workshop.qmd) |
| Oct 30, 2024 | [Week 13 - Emerging Topics in Bank Risk Management](./AFIN8003/2024S2/Week13/index.qmd) ([PDF](./AFIN8003/2024S2/Week13/Week13.pdf))             | None                                                 |

