---
title: "AFIN8003 - Workshop 2"
subtitle: "Banking and Financial Intermediation"
author: "Dr. Mingze Gao"
institute: "Department of Applied Finance"
date: 2024-07-31
categories:
    - AFIN8003
    - 2024S2
format: 
  pdf:
    documentclass: article
    papersize: a4
    toc: false
    number-sections: true
    colorlinks: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fig-pos: "H"
    fig-width: 1
    fig-cap-location: "bottom"
    output-file: "Workshop2.pdf"
# Custom fields
pdf-name: "Workshop2.pdf"
---

In today's workshop, we will conduct some group-based activities. You will form a group of 3 to 4 people and collectively work on the assigned tasks. At the end of the workshop, __two groups will be randomly chosen to do a 5-min presentation__.

The objective os this workshop is to enhance your analytical, research, and teamwork/presentation skills by working on real-world cases.

# Analyzing risk management in major australian banks

**Background:** The Risk Management Discussion section in a bank's annual report is a critical component that provides stakeholders with an in-depth understanding of how the institution identifies, assesses, and manages various risks. This section is essential for investors, regulators, and other stakeholders who need to evaluate the bank's stability and resilience in the face of potential risks.

**Overview:** We will examine major Australian banks' most recent annual reports to understand and compare their risk management strategies.

**Instructions:**

1. **Group Formation:** Form groups of 3-4 students.
   
2. **Bank Selection:** Each group will choose __any two__ of the major four banks in Australia:
    - Commonwealth Bank of Australia (CBA)
    - Westpac Banking Corporation (Westpac)
    - Australia and New Zealand Banking Group (ANZ)
    - National Australia Bank (NAB)

3. **Annual Report Collection:**
    - Locate and download the most recent annual reports (for 2023) for the selected banks.
    - CBA: [annual reports](https://www.commbank.com.au/about-us/opportunity-initiatives/performance-reporting.html)
    - Westpac: [annual reports](https://www.westpac.com.au/about-westpac/investor-centre/financial-information/annual-reports/)
    - ANZ: [annual reports](https://www.anz.com/shareholder/centre/reporting/annual-report-annual-review/)
    - NAB: [annual reports](https://www.nab.com.au/about-us/shareholder-centre/financial-disclosures-and-reporting/annual-reporting-suite)

4. **Risk Management Discussion Analysis:**
    - Navigate to the Risk Management section in each bank's annual report.
    - Extract and summarize the key points from the Risk Management Discussion. Pay particular attention to the following questions:
        - What types of risks are identified by the bank?
        - How does the bank define each type of risk?
        - What strategies, measures, or actions does the bank implement to mitigate these risks?

5. **Comparison and Discussion:**
    - Compare the risk management strategies of the two selected banks.
    - Discuss the similarities and differences in their approaches to managing risks.
    - Of the two selected banks, which one do you think does a better job explaining and discussing its risk management?

6. **Presentation:**
    - Prepare a brief presentation (5 minutes) summarizing your findings.
        - Some slides to show to the class would be very helpful!
    - Highlight key insights and conclusions drawn from your analysis.
    - Be prepared to answer questions from the class and engage in a discussion about your findings.

# Extra

In this workshop, we focus only on the most recent annual reports of the selected banks. In addition, try to collect their past reports and conduct the same analyses as above. In particular, can you identify any significant changes over the years?
