---
title: "AFIN8003 Week 9 - Liability and Liquidity Management"
subtitle: "Banking and Financial Intermediation"
author: "Dr. Mingze Gao (MQBS) and Stephen Donaghy (UniSuper)"
# institute: "Department of Applied Finance"
date: 2025-05-08
draft: false
categories:
    - AFIN8003
    - 2025S1
format: 
  mq-revealjs: 
    chalkboard: true
    embed-resources: false
    echo: true
    code-fold: true
    footer: "AFIN8003 Banking and Financial Intermediation"
    mermaid-format: svg
  pdf:
    echo: false
    documentclass: article
    papersize: a4
    toc: true
    number-sections: true
    colorlinks: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fig-pos: "H"
    fig-width: 1
    fig-cap-location: "bottom"
    output-file: "Week9.pdf"
# Custom fields
pdf-name: "Week9.pdf"
---

# Guest Lecturer

## Stephen Donaghy

Stephen Donaghy is a **Senior Manager Investment** at [UniSuper](https://www.unisuper.com.au/), which has $139 billion funds under management and 647k members.

He is responsible for leading the analytical capabilities that feed into the asset allocation and construction of UniSuper’s Investment options. This also includes understanding the implications of the Your Future Your Super Performance Test and the monitoring and management capabilities required to operate alongside this test.

Stephen also plays a key role in building out UniSuper’s ESG data and analytics capabilities which supports the integration of ESG principles across all aspects of UniSuper’s investment process.

# Liability and Liquidity Management

## Introduction

- [Last week](https://mingze-gao.com/teaching/AFIN8003/2025S1/Week8/) we discussed the __liquidity risk__ of financial institutions (FIs), especially depositary institutions (DIs).
  - Liquidity risk can arise from both _asset side_ and _liability side_.
- This week, we will first discuss liquidity management from banks' point of view.
  - Asset-side liquidity management: liquid asset positions
  - Liability-side liquidity management: the liability structure of portfolios
- Stephen will then give us an industry perspective based on UniSuper.

## Source of liquidity

Historically, primary method of meeting cash demands: _asset liquidity_ (stored liquidity)

- Examples: cash, treasury securities
- Stock of liquid assets in an FI depends on
  - FI's willingness to trade off liquidity and returns
  - FI's ability to use liability liquidity

Today, primary method of meeting cash demands: _liability liquidity_ / management (purchased liquidity)

- Examples: interbank market for exchange settled funds, repos, interbank market

## Asset-side liquidity and management

- Liquid assets, e.g., Treasury notes/bonds, are traded in a _deep_ market[^deep]

[^deep]: A market is _deep_ when even large trading volumes will not impact on price.

- The composition of an FI’s liquid asset portfolio (especially cash and government securities) is partly determined by:
    - minimum liquid-asset reserve requirements imposed by the central bank
    - earnings consideration
- Government securities act as secondary buffer reserves
    - When significant drains on cash reserves occur, these securities can be turned into cash quickly and with very little loss of principal value because of the deep nature of the markets in which these assets are traded.

## Risk-return trade-off for liquid assets

- Liquid assets carry a comparatively lower interest rate
- At the heart of management of the liquid asset portfolio is balancing the benefits and costs of holding liquid assets
    - Cash immediacy versus reduced return
- Need to consider, among other things, the variability of deposit inflows and outflows, the yield and liquidation costs of non-liquid assets, the interest paid on purchased funds in the money market, and more
- Day-to-day liquidity management means that a DI faces the risk of either undershooting or overshooting the required liquidity requirement on any given day.
    - Undershooting the regulatory required liquidity ratios (e.g., LCR, NSFR) may involve specified additional charges.
    - Holding cash reserves in excess of the minimum required can be costly.[^cost-of-esa]
- The management of a DI’s __exchange settlement account (ESA)__ at the RBA is critical.

[^cost-of-esa]: RBA pays ['cash target rate minus 10 basis points'](https://www.rba.gov.au/education/resources/explainers/how-rba-implements-monetary-policy.html#:~:text=The%20Reserve%20Bank%20currently%20pays%20an%20interest%20rate%20on%20ES%20balances%20that%20is%200.1%20percentage%20points%20below%20the%20cash%20rate%20target.) interest on ESA balances.

::: {.callout-note}
ESA is an account held at the Reserve Bank of Australia by financial institutions to settle financial obligations arising from the clearing of payments.
:::

## The cash market and Exchange Settlement Account (ESA)

The __cash market__ is where banks lend and borrow funds from each other, typically on an overnight basis. These funds can be used to:

- Meet liquidity needs: Banks may borrow funds to ensure they meet short-term liquidity requirements, such as the ESA balances.
- Support lending activities: Banks may also use borrowed funds to support ongoing lending activities.
- Facilitate settlement of transactions: The funds can help banks settle large-scale interbank transactions efficiently.

Importantly,

- The _price_ of funds in this market is the interest rate on these interbank loans, which is called the __cash rate__ in Australia.
- The _quantity_ traded in this market is called the Exchange Settlement (ES) balance - the balance of DI's deposit accounts at the RBA, the ESA.

## The cash market, ESA, and repo transactions

RBA sets a target for the cash rate, it is often referred to as a "tool" of monetary policy.

Prior to the COVID-19 recession,

- the cash rate target was the RBA's only active monetary policy tool.
- the RBA managed the supply of ES balances so that it met estimated demand and the cash rate was close to its target.
- the RBA achieved cash rate target through open market operations, particularly through __repurchase agreements (repos)__.

::: {.callout-note title="Repo transactions of RBA"}
A repo is a transaction with two parts. 

- In the first part, the Reserve Bank could lend ES balances to a bank and receive a bond in exchange. This increases the supply of ES balances available to banks. 
- In the pre-arranged second part, the transaction is reversed. The Reserve Bank returns the bond and receives back the ES balances, which decreases the supply of ES balances.
:::

After the introduction of the package of policy measures in response to the COVID-19 recession,

- ES balances substantially increased.
- the RBA, as a result, no longer conducts daily open market operations to manage ES balances.

::: {.content-hidden unless-format="pdf"}
## Repo transactions to manage liquidity (ES balance)

- Two sources of exchange settlement liquidity for Australian DIs provided by RBA repos
    - Intra-day repo: a facility that allows a DI to utilise RBA repos to obtain intra-day liquidity, with the repo reversed later in the same day
    - Overnight repo: a facility that allows a DI to use RBA repos in order to obtain liquidity overnight to fund its liquidity settlement needs
- After introduction of same day settlement, RBA also introduced open RBA repo.
    - Open RBA repo: an RBA repurchase agreement with no specified end date
- With Basel III reforms, starting on 1 January 2015, the committed liquidity facility is also introduced.
    - Committed liquidity facility: a facility providing secured line of credit from the central bank allowed under Basel III in regimes which do not have sufficient liquid assets to meet the Basel III liquidity reforms
:::

## The changing dynamics

Since COVID-19, the RBA significantly adjusted its monetary operations, moving away from repos as the primary tool for managing liquidity. Banks now manage their ESA balances primarily through other mechanisms:

- [Term Funding Facility (ended 30 June 2024)](https://www.rba.gov.au/mkt-operations/term-funding-facility/): Introduced during the pandemic, the TFF allowed banks to access longer-term funding at very low rates. It helped banks manage funding needs over the pandemic period.
- [Government Bond Purchases (ceased on 10 February 2022)](https://www.rba.gov.au/mkt-operations/government-bond-purchases.html): The RBA engaged in large-scale government bond purchases to inject liquidity into the financial system. This action increased the level of reserves in the banking system, reducing the immediate need for repo operations.
- Standing Facility: Banks can still access liquidity via the RBA’s standing liquidity facility, where they can borrow overnight at a penalty rate if their ESA balances fall short.
- Interbank Cash Market: Banks continue to borrow and lend among themselves in the interbank cash market to manage daily fluctuations in their ESA balances.
- Repo Transactions in the Private Market. While the RBA no longer conducts open market repos, banks and other financial institutions still use repo transactions with each other as a way to manage liquidity and secure short-term funding. These private market repos are similar in structure to the RBA's past operations but are conducted bilaterally between financial institutions.

## Liability-side liquidity and management

- Liability management is closely linked to liquidity management
- Overall aim of liability management: to construct a low-cost and low–withdrawal-risk liability portfolio
- Problems
    - Low-cost liabilities often carry high withdrawal risk: e.g., demand deposits
    - Low withdrawal risk often comes with high cost: e.g., certificates of deposit (CDs)

::: {.content-hidden when-format="pdf"}
## Liability management (cont'd)
:::

Deposit liabilities

- Cheque account and other demand deposits
- Savings account
- Cash management account (CMA) / investment savings accounts
- Fixed-term deposits
- Negotiable certificates of deposits (NCDs)

Non-deposit liabilities

- Interbank funds
- Repurchase agreements (Repos)
- Covered bonds
- Other borrowings
- Bank accepted bills
- Commercial bills or non-bank bills
- Commercial paper or promissory notes
- Subordinated debt, medium-term notes and long-term borrowings

## Choice of liability structure

Now we turn to a more detailed discussion of the _withdrawal risk_ and _funding cost_ characteristics of the major liabilities of a modern DI.

::: {.callout-note}
The following slides on specific products should be read after the lecture.
:::

## Choice of liability structure: demand deposits

Withdrawal risk:

- High degree of withdrawal risk

Costs:

- Low
- Since 1930, in U.S., demand deposits paid zero explicit interest!
- Since 2011, such prohibition was repealed. DIs are now allowed but not required to interest on demand deposits. Few of them do.
- This does not mean that demand deposits are _free_ to DIs.
    - Services associated with providing checkable accounts consume costly labor and capital.
    - Competition resulted in _implicit interest_.
- DIs can recapture costs by charging fee such as cost per cheque cleared or electronic transaction.
    - Depositors receives a "subsidy" when such fees do not fully cover the DI's cost of providing these services.

$$
\text{Average implicit interest rate (IIR)} = \frac{\text{DI's average management cost per account – average fees earned per account}}{\text{average annual size of account}}
$$

::: {.content-hidden unless-format="pdf"}
## Example: average implicit interest rate

Suppose it costs a DI 15 cents to clear a cheque but it charges a fee of only 10 cents per cheque cleared. In this case, the customer receives a 5 cent subsidy per cheque. We can calculate implicit yields for each service, or an average implicit interest rate, for each current deposit account. 

Suppose that:

- DI’s average management costs per account per annum = $150
- Average fees earned per account per annum = $100
- Average annual size of account = $1200

Then,

$$
\text{Average implicit interest rate (IIR)} = \frac{150-100}{1200} = 4.166\%
$$

## Example: gross interest rate

Consider the following case:

- A depositor holds on average $250 per month for the first three months of the year, $500 per month for the next three months, and $1000 per month for the final six months of the year in a demand deposit account. 
- The account pays 5 per cent per annum if the minimum balance is $500 or more, and it pays no interest if the account falls below $500. 
- The depositor makes an average of 50 internet transactions per month and pays a service fee of 10 cents for each transaction, although it costs the bank 15 cents to process each transaction. 

The account holder’s gross interest return, consisting of implicit plus explicit interest, is:

$$
\begin{aligned}
\text{Gross interest return} &= \text{Explicit interest} + \text{Implicit interest} \\
&=\$500(0.05)(0.25)+\$1000(0.05)(0.5)+(\$0.15−\$0.10)(50)(12) \\
&=\$6.25+\$25+\$30=\$61.25
\end{aligned}
$$

Suppose the minimum balance was lowered from $500 to $250 and internet service fees were lowered from 10 cents to 5 cents per transaction. Then:

$$
\begin{aligned}
\text{Gross interest return} &= \text{Explicit interest} + \text{Implicit interest} \\
&=\$250(0.05)(0.25)+(\$500)(0.05)(0.25)+\$1000(0.05)(0.5)+(\$0.15−\$0.05)(50)(12) \\
&=\$3.125+\$6.25+\$25+\$60 =\$94.375
\end{aligned}
$$
:::

## Choice of liability structure: interest-bearing cheque accounts

Withdrawal risk:

- Lower degree of withdrawal risk compared to current accounts
    - Minimum balance requirements

Costs:

- Comparably higher cost: three pricing mechanisms
    - Implicit interest payments
    - Minimum balance requirements
    - Explicit interest payments
- Gross interest return = explicit interest + implicit interest

## Choice of liability structure: savings account

Withdrawal risk:

- Lower withdrawal risk compared to cheque accounts  
    - Restrictions on withdrawals (e.g., limited monthly withdrawals, notice period)
    - Typically held for long-term savings purposes
    - Fewer transactional services offered

Costs:

- Very small implicit interest payments
- Explicit interest payments to account holders

## Choice of liability structure: MMDAs

In U.S., since 1982, DIs can use _money market deposit accounts (MMDAs)_ as an additional liability instrument.

- Competition with money market mutual funds offered by groups such as Vanguard and Fidelity.
- MMDAs are checkable but subject to restrictions.

Withdrawal risk:

- Lower due to the restrictions on checking and transfers

Costs:

- Higher explicit interest

In Australia, BOQ together with DDH Graham offers MMDA. Cash management accounts (CMAs) are more popular.

## Choice of liability structure: CMA / investment savings account

Investment savings accounts (or cash management accounts) are high denomination savings accounts that have no specified maturity date but require high minimum balances (e.g. $10 000) and minimum transaction size (e.g. $500).

- The funds are available on call.
- Relatively low degree of withdrawal risk.
- Costs: higher interest than basic savings accounts, mitigated by fees charged

## Choice of liability structure: term and fixed-time deposits / retail CDs

Fixed-maturity instruments.

Withdrawal risk:

- Very low: early withdrawal penalties

Costs:

- High explicit interest

::: {.callout-note}
For example, Bank of America's [PDS](https://www.bankofamerica.com/salesservices/deposits/resources/deposit-agreements/?request_locale=en_US#page=9.68).
:::

## Choice of liability structure: negotiable certificates of deposits (NCDs)

Time deposits with fixed maturity and face values > $100 000 with varying maturities.

Negotiable instruments: an instrument that can be sold in the secondary market thereby transferring ownership.

- Low withdrawal risk
- The rates are market driven => Comparatively lower cost due to generally high credit rating of issuer

::: {.callout-note}
Nowadays banks offer more comprehensive solutions. 

For example, CBA offers ["Investment Guarantee"](https://www.commbank.com.au/personal/apply-online/download-printed-forms/ADB2665.pdf), a fixed term investment that is composed of a series of underlying securities, which are either a _bill of exchange (e.g., bank accepted bill)_ or a _NCD_.
:::

## Choice of liability structure: non-deposit liabilities

Interbank funds

- Short-term un-collateralised loans between FIs
- Rollover risk
- Cost: short-term money market rate

Repurchase agreements (repos)

- Collateralised interbank transactions
- Highly liquid and flexible source of funds
- Yield generally below the market interbank rate due to collateralised nature


::: {.content-hidden when-format="pdf"}
## Choice of liability structure: non-deposit liabilities (cont'd)
:::

Covered bonds

- Bonds issued by a bank, backed by a pool of assets that remain on the balance sheet of the issuing bank
- Available for Australian DIs after legislative change in 2011, with a cap at 8 per cent of DI assets.
- Safest form of bank debt
- Typically carry a higher credit rating than that of their issuer DI

::: {.callout-note}
Covered bond is more of a feature in Australia ([APS 121 Covered Bonds](https://www.legislation.gov.au/F2022L01566/latest/text)).

For example, the [CBA's covered bonds program](https://www.commbank.com.au/about-us/investors/covered-bonds.html).
:::

::: {.content-hidden when-format="pdf"}
## Choice of liability structure: non-deposit liabilities (cont'd)
:::

Other Borrowing

- Bank accepted bills (BAB)
- Commercial bills (or non-bank bills)
- Commercial paper or promissory notes
- Subordinated debt, medium-term notes and long-term borrowings

## Liability and liquidity management in insurance companies

- Insurance companies require liquidity to meet claims and unexpected policy surrenders.
- Ideally, liquidity is managed through premiums received on new and existing contracts.
- High-frequency claims, like during a severe hurricane season, may force asset liquidation at lower-than-market value.
- Diversifying risk in insurance contracts reduces liquidity risk (e.g., covering different types of disasters).
- Insurers can hold marketable assets (e.g., government bonds, corporate bonds, stocks) to cover claim payments when premium income is insufficient.

## Liability and liquidity management in other financial institutions

- Securities firms, investment banks, and finance companies face liquidity risk if they rely on short-term financing (e.g., commercial paper, bank loans) and investors hesitate to roll over funds.

For securities firms,

- Main funding sources include repurchase agreements, bank loans, and short positions in securities.
- Liquidity management requires enough cash and liquid resources to underwrite new securities and resell them to investors.

For investment banks (and securities firms),

- Liability management involves financing an inventory of securities to act as a market maker.

For finance companies,

- Main funding sources include commercial paper and long-term debt.
- Need liquidity to fund loan requests and commitments promptly.

# Guest Lecture

## UniSuper

Now, let's welcome Stephen Donaghy to give us a talk about UniSuper and share his insights!

# Finally...

## Suggested readings

- [How RBA implements monetary policy](https://www.rba.gov.au/education/resources/explainers/how-rba-implements-monetary-policy.html).
- [RBA Exchange Settlement Account Policy](https://www.rba.gov.au/payments-and-infrastructure/esa/).
- [RBA Standing Facilities](https://www.rba.gov.au/mkt-operations/resources/tech-notes/standing-facilities.html).
- [Covered bonds in Australia](https://www.rba.gov.au/publications/bulletin/2017/sep/pdf/bu-0917-7-covered-bonds-in-australia.pdf).
- [Prudential Standard APS 210 Liquidity](https://www.apra.gov.au/sites/default/files/APS%2520210%2520FINAL.pdf).

## References
