<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>corporate-filings-talk-spec – Mingze Gao</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../images/favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-dbc92dda8186f57fa2e333fbb71d6a9d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-e059821d6effba5895112697234fbda0.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-d68aeba3a79b5d13331dcac62a63c5fd.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-e059821d6effba5895112697234fbda0.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1QDTTQ6EHM"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-1QDTTQ6EHM', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../../../styles.css">
<meta name="twitter:title" content="Mingze Gao">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../images/favicon.png" alt="" class="navbar-logo light-content">
    <img src="../../../images/favicon.png" alt="" class="navbar-logo dark-content">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../cv/index.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../research/index.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../posts/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://phds.io/"> 
<span class="menu-text">Literature 🔍</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#production-specification-quarto-revealjs-seminar-deck-on-corporate-filings" id="toc-production-specification-quarto-revealjs-seminar-deck-on-corporate-filings" class="nav-link active" data-scroll-target="#production-specification-quarto-revealjs-seminar-deck-on-corporate-filings">Production specification: Quarto revealJS seminar deck on corporate filings</a>
  <ul class="collapse">
  <li><a href="#working-title" id="toc-working-title" class="nav-link" data-scroll-target="#working-title">Working title</a></li>
  <li><a href="#purpose-of-this-file" id="toc-purpose-of-this-file" class="nav-link" data-scroll-target="#purpose-of-this-file">Purpose of this file</a></li>
  <li><a href="#core-objective" id="toc-core-objective" class="nav-link" data-scroll-target="#core-objective">Core objective</a></li>
  <li><a href="#audience" id="toc-audience" class="nav-link" data-scroll-target="#audience">Audience</a></li>
  <li><a href="#speaker-and-tone" id="toc-speaker-and-tone" class="nav-link" data-scroll-target="#speaker-and-tone">Speaker and tone</a></li>
  <li><a href="#required-output" id="toc-required-output" class="nav-link" data-scroll-target="#required-output">Required output</a></li>
  <li><a href="#quarto-implementation-requirements" id="toc-quarto-implementation-requirements" class="nav-link" data-scroll-target="#quarto-implementation-requirements">Quarto implementation requirements</a></li>
  <li><a href="#content-philosophy" id="toc-content-philosophy" class="nav-link" data-scroll-target="#content-philosophy">Content philosophy</a></li>
  <li><a href="#overall-narrative" id="toc-overall-narrative" class="nav-link" data-scroll-target="#overall-narrative">Overall narrative</a></li>
  <li><a href="#timing-target" id="toc-timing-target" class="nav-link" data-scroll-target="#timing-target">Timing target</a></li>
  <li><a href="#must-use-factual-anchors" id="toc-must-use-factual-anchors" class="nav-link" data-scroll-target="#must-use-factual-anchors">Must-use factual anchors</a>
  <ul class="collapse">
  <li><a href="#sec-access-and-apis" id="toc-sec-access-and-apis" class="nav-link" data-scroll-target="#sec-access-and-apis">SEC access and APIs</a></li>
  <li><a href="#edgar-full-text-search" id="toc-edgar-full-text-search" class="nav-link" data-scroll-target="#edgar-full-text-search">EDGAR full-text search</a></li>
  <li><a href="#sec-filing-volume-and-search-volume" id="toc-sec-filing-volume-and-search-volume" class="nav-link" data-scroll-target="#sec-filing-volume-and-search-volume">SEC filing volume and search volume</a></li>
  <li><a href="#seekedgar" id="toc-seekedgar" class="nav-link" data-scroll-target="#seekedgar">SeekEdgar</a></li>
  <li><a href="#presenters-old-website-note" id="toc-presenters-old-website-note" class="nav-link" data-scroll-target="#presenters-old-website-note">Presenter’s old website note</a></li>
  <li><a href="#presenters-jcf-paper" id="toc-presenters-jcf-paper" class="nav-link" data-scroll-target="#presenters-jcf-paper">Presenter’s JCF paper</a></li>
  </ul></li>
  <li><a href="#important-writing-constraints" id="toc-important-writing-constraints" class="nav-link" data-scroll-target="#important-writing-constraints">Important writing constraints</a></li>
  <li><a href="#visual-design-requirements" id="toc-visual-design-requirements" class="nav-link" data-scroll-target="#visual-design-requirements">Visual design requirements</a></li>
  <li><a href="#embedded-chart-data" id="toc-embedded-chart-data" class="nav-link" data-scroll-target="#embedded-chart-data">Embedded chart data</a></li>
  <li><a href="#slide-by-slide-specification" id="toc-slide-by-slide-specification" class="nav-link" data-scroll-target="#slide-by-slide-specification">Slide-by-slide specification</a>
  <ul class="collapse">
  <li><a href="#slide-1.-title" id="toc-slide-1.-title" class="nav-link" data-scroll-target="#slide-1.-title">Slide 1. Title</a></li>
  <li><a href="#slide-2.-opening-hook" id="toc-slide-2.-opening-hook" class="nav-link" data-scroll-target="#slide-2.-opening-hook">Slide 2. Opening hook</a></li>
  <li><a href="#slide-3.-why-this-matters-beyond-finance-and-accounting" id="toc-slide-3.-why-this-matters-beyond-finance-and-accounting" class="nav-link" data-scroll-target="#slide-3.-why-this-matters-beyond-finance-and-accounting">Slide 3. Why this matters beyond finance and accounting</a></li>
  <li><a href="#slide-4.-big-numbers" id="toc-slide-4.-big-numbers" class="nav-link" data-scroll-target="#slide-4.-big-numbers">Slide 4. Big numbers</a></li>
  <li><a href="#slide-5.-what-makes-filings-distinctive" id="toc-slide-5.-what-makes-filings-distinctive" class="nav-link" data-scroll-target="#slide-5.-what-makes-filings-distinctive">Slide 5. What makes filings distinctive?</a></li>
  <li><a href="#slide-6.-section-divider" id="toc-slide-6.-section-divider" class="nav-link" data-scroll-target="#slide-6.-section-divider">Slide 6. Section divider</a></li>
  <li><a href="#slide-7.-what-is-edgar" id="toc-slide-7.-what-is-edgar" class="nav-link" data-scroll-target="#slide-7.-what-is-edgar">Slide 7. What is EDGAR?</a></li>
  <li><a href="#slide-8.-the-filing-universe-grouped-by-research-use" id="toc-slide-8.-the-filing-universe-grouped-by-research-use" class="nav-link" data-scroll-target="#slide-8.-the-filing-universe-grouped-by-research-use">Slide 8. The filing universe, grouped by research use</a></li>
  <li><a href="#slide-9.-periodic-reports" id="toc-slide-9.-periodic-reports" class="nav-link" data-scroll-target="#slide-9.-periodic-reports">Slide 9. Periodic reports</a></li>
  <li><a href="#slide-10.-event-driven-filings" id="toc-slide-10.-event-driven-filings" class="nav-link" data-scroll-target="#slide-10.-event-driven-filings">Slide 10. Event-driven filings</a></li>
  <li><a href="#slide-11.-ownership-trading-and-influence" id="toc-slide-11.-ownership-trading-and-influence" class="nav-link" data-scroll-target="#slide-11.-ownership-trading-and-influence">Slide 11. Ownership, trading, and influence</a></li>
  <li><a href="#slide-12.-governance-and-shareholder-process" id="toc-slide-12.-governance-and-shareholder-process" class="nav-link" data-scroll-target="#slide-12.-governance-and-shareholder-process">Slide 12. Governance and shareholder process</a></li>
  <li><a href="#slide-13.-issuance-listing-and-entrepreneurial-firms" id="toc-slide-13.-issuance-listing-and-entrepreneurial-firms" class="nav-link" data-scroll-target="#slide-13.-issuance-listing-and-entrepreneurial-firms">Slide 13. Issuance, listing, and entrepreneurial firms</a></li>
  <li><a href="#slide-14.-exhibits-are-the-hidden-goldmine" id="toc-slide-14.-exhibits-are-the-hidden-goldmine" class="nav-link" data-scroll-target="#slide-14.-exhibits-are-the-hidden-goldmine">Slide 14. Exhibits are the hidden goldmine</a></li>
  <li><a href="#slide-15.-section-divider" id="toc-slide-15.-section-divider" class="nav-link" data-scroll-target="#slide-15.-section-divider">Slide 15. Section divider</a></li>
  <li><a href="#slide-16.-research-idea-matrix" id="toc-slide-16.-research-idea-matrix" class="nav-link" data-scroll-target="#slide-16.-research-idea-matrix">Slide 16. Research idea matrix</a></li>
  <li><a href="#slide-17.-case-study-loan-contracts-from-filings" id="toc-slide-17.-case-study-loan-contracts-from-filings" class="nav-link" data-scroll-target="#slide-17.-case-study-loan-contracts-from-filings">Slide 17. Case study: loan contracts from filings</a></li>
  <li><a href="#slide-18.-what-the-loan-contract-example-teaches" id="toc-slide-18.-what-the-loan-contract-example-teaches" class="nav-link" data-scroll-target="#slide-18.-what-the-loan-contract-example-teaches">Slide 18. What the loan-contract example teaches</a></li>
  <li><a href="#slide-19.-narrative-disclosures" id="toc-slide-19.-narrative-disclosures" class="nav-link" data-scroll-target="#slide-19.-narrative-disclosures">Slide 19. Narrative disclosures</a></li>
  <li><a href="#slide-20.-governance-and-influence-examples" id="toc-slide-20.-governance-and-influence-examples" class="nav-link" data-scroll-target="#slide-20.-governance-and-influence-examples">Slide 20. Governance and influence examples</a></li>
  <li><a href="#slide-21.-innovation-and-digital-transformation-examples" id="toc-slide-21.-innovation-and-digital-transformation-examples" class="nav-link" data-scroll-target="#slide-21.-innovation-and-digital-transformation-examples">Slide 21. Innovation and digital transformation examples</a></li>
  <li><a href="#slide-22.-foreign-issuers-and-comparative-work" id="toc-slide-22.-foreign-issuers-and-comparative-work" class="nav-link" data-scroll-target="#slide-22.-foreign-issuers-and-comparative-work">Slide 22. Foreign issuers and comparative work</a></li>
  <li><a href="#slide-23.-section-divider" id="toc-slide-23.-section-divider" class="nav-link" data-scroll-target="#slide-23.-section-divider">Slide 23. Section divider</a></li>
  <li><a href="#slide-24.-workflow-from-research-question-to-dataset" id="toc-slide-24.-workflow-from-research-question-to-dataset" class="nav-link" data-scroll-target="#slide-24.-workflow-from-research-question-to-dataset">Slide 24. Workflow from research question to dataset</a></li>
  <li><a href="#slide-25.-data-layers-inside-a-filing" id="toc-slide-25.-data-layers-inside-a-filing" class="nav-link" data-scroll-target="#slide-25.-data-layers-inside-a-filing">Slide 25. Data layers inside a filing</a></li>
  <li><a href="#slide-26.-search-first-scale-later" id="toc-slide-26.-search-first-scale-later" class="nav-link" data-scroll-target="#slide-26.-search-first-scale-later">Slide 26. Search first, scale later</a></li>
  <li><a href="#slide-27.-edgar-and-seekedgar" id="toc-slide-27.-edgar-and-seekedgar" class="nav-link" data-scroll-target="#slide-27.-edgar-and-seekedgar">Slide 27. EDGAR and SeekEdgar</a></li>
  <li><a href="#slide-28.-light-python-example" id="toc-slide-28.-light-python-example" class="nav-link" data-scroll-target="#slide-28.-light-python-example">Slide 28. Light Python example</a></li>
  <li><a href="#slide-29.-extraction-ladder" id="toc-slide-29.-extraction-ladder" class="nav-link" data-scroll-target="#slide-29.-extraction-ladder">Slide 29. Extraction ladder</a></li>
  <li><a href="#slide-30.-validation-is-the-research-design" id="toc-slide-30.-validation-is-the-research-design" class="nav-link" data-scroll-target="#slide-30.-validation-is-the-research-design">Slide 30. Validation is the research design</a></li>
  <li><a href="#slide-31.-section-divider" id="toc-slide-31.-section-divider" class="nav-link" data-scroll-target="#slide-31.-section-divider">Slide 31. Section divider</a></li>
  <li><a href="#slide-32.-pitfall-grid" id="toc-slide-32.-pitfall-grid" class="nav-link" data-scroll-target="#slide-32.-pitfall-grid">Slide 32. Pitfall grid</a></li>
  <li><a href="#slide-33.-ethical-and-practical-notes" id="toc-slide-33.-ethical-and-practical-notes" class="nav-link" data-scroll-target="#slide-33.-ethical-and-practical-notes">Slide 33. Ethical and practical notes</a></li>
  <li><a href="#slide-34.-how-to-start-this-month" id="toc-slide-34.-how-to-start-this-month" class="nav-link" data-scroll-target="#slide-34.-how-to-start-this-month">Slide 34. How to start this month</a></li>
  <li><a href="#slide-35.-closing-takeaway" id="toc-slide-35.-closing-takeaway" class="nav-link" data-scroll-target="#slide-35.-closing-takeaway">Slide 35. Closing takeaway</a></li>
  </ul></li>
  <li><a href="#appendix-slide-specifications" id="toc-appendix-slide-specifications" class="nav-link" data-scroll-target="#appendix-slide-specifications">Appendix slide specifications</a>
  <ul class="collapse">
  <li><a href="#appendix-a1.-links-and-resources" id="toc-appendix-a1.-links-and-resources" class="nav-link" data-scroll-target="#appendix-a1.-links-and-resources">Appendix A1. Links and resources</a></li>
  <li><a href="#appendix-a2.-common-filing-families" id="toc-appendix-a2.-common-filing-families" class="nav-link" data-scroll-target="#appendix-a2.-common-filing-families">Appendix A2. Common filing families</a></li>
  <li><a href="#appendix-a3.-sec-api-endpoints" id="toc-appendix-a3.-sec-api-endpoints" class="nav-link" data-scroll-target="#appendix-a3.-sec-api-endpoints">Appendix A3. SEC API endpoints</a></li>
  <li><a href="#appendix-a4.-python-example-list-recent-filings" id="toc-appendix-a4.-python-example-list-recent-filings" class="nav-link" data-scroll-target="#appendix-a4.-python-example-list-recent-filings">Appendix A4. Python example: list recent filings</a></li>
  <li><a href="#appendix-a5.-python-example-construct-a-filing-url" id="toc-appendix-a5.-python-example-construct-a-filing-url" class="nav-link" data-scroll-target="#appendix-a5.-python-example-construct-a-filing-url">Appendix A5. Python example: construct a filing URL</a></li>
  <li><a href="#appendix-a6.-from-search-terms-to-validation-table" id="toc-appendix-a6.-from-search-terms-to-validation-table" class="nav-link" data-scroll-target="#appendix-a6.-from-search-terms-to-validation-table">Appendix A6. From search terms to validation table</a></li>
  <li><a href="#appendix-a7.-seekedgar-workflow" id="toc-appendix-a7.-seekedgar-workflow" class="nav-link" data-scroll-target="#appendix-a7.-seekedgar-workflow">Appendix A7. SeekEdgar workflow</a></li>
  <li><a href="#appendix-a8.-good-research-question-templates" id="toc-appendix-a8.-good-research-question-templates" class="nav-link" data-scroll-target="#appendix-a8.-good-research-question-templates">Appendix A8. Good research question templates</a></li>
  <li><a href="#appendix-a9.-suggested-readings" id="toc-appendix-a9.-suggested-readings" class="nav-link" data-scroll-target="#appendix-a9.-suggested-readings">Appendix A9. Suggested readings</a></li>
  </ul></li>
  <li><a href="#python-chart-generation-guidance" id="toc-python-chart-generation-guidance" class="nav-link" data-scroll-target="#python-chart-generation-guidance">Python chart generation guidance</a></li>
  <li><a href="#suggested-design-patterns-in-quarto" id="toc-suggested-design-patterns-in-quarto" class="nav-link" data-scroll-target="#suggested-design-patterns-in-quarto">Suggested design patterns in Quarto</a>
  <ul class="collapse">
  <li><a href="#columns" id="toc-columns" class="nav-link" data-scroll-target="#columns">Columns</a></li>
  <li><a href="#callouts" id="toc-callouts" class="nav-link" data-scroll-target="#callouts">Callouts</a></li>
  <li><a href="#fragments" id="toc-fragments" class="nav-link" data-scroll-target="#fragments">Fragments</a></li>
  <li><a href="#section-divider" id="toc-section-divider" class="nav-link" data-scroll-target="#section-divider">Section divider</a></li>
  </ul></li>
  <li><a href="#style-and-pacing-rules" id="toc-style-and-pacing-rules" class="nav-link" data-scroll-target="#style-and-pacing-rules">Style and pacing rules</a></li>
  <li><a href="#suggested-research-idea-callouts" id="toc-suggested-research-idea-callouts" class="nav-link" data-scroll-target="#suggested-research-idea-callouts">Suggested “research idea” callouts</a></li>
  <li><a href="#specific-instructions-for-the-loan-contract-case-study" id="toc-specific-instructions-for-the-loan-contract-case-study" class="nav-link" data-scroll-target="#specific-instructions-for-the-loan-contract-case-study">Specific instructions for the loan-contract case study</a></li>
  <li><a href="#specific-instructions-for-seekedgar" id="toc-specific-instructions-for-seekedgar" class="nav-link" data-scroll-target="#specific-instructions-for-seekedgar">Specific instructions for SeekEdgar</a></li>
  <li><a href="#specific-instructions-for-edgar-api" id="toc-specific-instructions-for-edgar-api" class="nav-link" data-scroll-target="#specific-instructions-for-edgar-api">Specific instructions for EDGAR API</a></li>
  <li><a href="#quality-checklist-before-delivery" id="toc-quality-checklist-before-delivery" class="nav-link" data-scroll-target="#quality-checklist-before-delivery">Quality checklist before delivery</a>
  <ul class="collapse">
  <li><a href="#content-checks" id="toc-content-checks" class="nav-link" data-scroll-target="#content-checks">Content checks</a></li>
  <li><a href="#visual-checks" id="toc-visual-checks" class="nav-link" data-scroll-target="#visual-checks">Visual checks</a></li>
  <li><a href="#pedagogical-checks" id="toc-pedagogical-checks" class="nav-link" data-scroll-target="#pedagogical-checks">Pedagogical checks</a></li>
  <li><a href="#technical-checks" id="toc-technical-checks" class="nav-link" data-scroll-target="#technical-checks">Technical checks</a></li>
  </ul></li>
  <li><a href="#suggested-final-slide-wording" id="toc-suggested-final-slide-wording" class="nav-link" data-scroll-target="#suggested-final-slide-wording">Suggested final slide wording</a></li>
  <li><a href="#final-instruction-to-the-deck-producer" id="toc-final-instruction-to-the-deck-producer" class="nav-link" data-scroll-target="#final-instruction-to-the-deck-producer">Final instruction to the deck producer</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="production-specification-quarto-revealjs-seminar-deck-on-corporate-filings" class="level1">
<h1>Production specification: Quarto revealJS seminar deck on corporate filings</h1>
<section id="working-title" class="level2">
<h2 class="anchored" data-anchor-id="working-title">Working title</h2>
<p><strong>Corporate Filings as a Research Data Source</strong></p>
<p>Suggested subtitle:</p>
<blockquote class="blockquote">
<p>From research ideas to EDGAR, SeekEdgar, and information extraction</p>
</blockquote>
</section>
<section id="purpose-of-this-file" class="level2">
<h2 class="anchored" data-anchor-id="purpose-of-this-file">Purpose of this file</h2>
<p>This is a detailed production brief for creating a static Quarto revealJS seminar deck. It is intended for an LLM or human slide producer who will build the actual <code>.qmd</code> presentation.</p>
<p>The first attempt was too generic and visually underdeveloped. The revised deck must be more engaging, more concrete, and more useful for research students across a business school.</p>
</section>
<section id="core-objective" class="level2">
<h2 class="anchored" data-anchor-id="core-objective">Core objective</h2>
<p>Create a <strong>40-minute seminar-style Quarto revealJS deck</strong> introducing corporate filings as a broad research data source for business school research students.</p>
<p>The talk should:</p>
<ol type="1">
<li>Inspire students to use corporate filings in research.</li>
<li>Demystify what EDGAR filings are.</li>
<li>Go beyond common forms such as 10-K, 10-Q, 8-K, and 13F.</li>
<li>Show how filings can support research in finance, accounting, management, strategy, innovation, information systems, entrepreneurship, marketing, and political economy.</li>
<li>Explain practical access through EDGAR, SEC search tools, SEC APIs, and SeekEdgar.</li>
<li>Include a light to moderate Python example.</li>
<li>Use the presenter’s old website note on SEC textual analysis as a teaching anchor.</li>
<li>Include the presenter’s Journal of Corporate Finance loan-contract example as a motivating case study.</li>
<li>Be static for now. A live demo will be developed later.</li>
</ol>
</section>
<section id="audience" class="level2">
<h2 class="anchored" data-anchor-id="audience">Audience</h2>
<p>Assume a <strong>balanced mix of business school research students</strong>:</p>
<ul>
<li>Finance and accounting students may know some common filings.</li>
<li>Management, marketing, entrepreneurship, information systems, and international business students may know very little about filings.</li>
<li>Many students may be empirical researchers but not specialized in EDGAR.</li>
<li>Technical comfort is mixed. Some will code, some will not.</li>
</ul>
<p>The deck should be accessible but not superficial. It should avoid long legal descriptions and avoid turning into a scraping workshop.</p>
</section>
<section id="speaker-and-tone" class="level2">
<h2 class="anchored" data-anchor-id="speaker-and-tone">Speaker and tone</h2>
<p>The speaker is a finance academic introducing a valuable data source to research students.</p>
<p>Tone:</p>
<ul>
<li>Academic seminar style.</li>
<li>Practical and motivating.</li>
<li>Conceptual first, technical second.</li>
<li>Clear, precise, and research-oriented.</li>
<li>Avoid sales language.</li>
<li>Avoid sounding like a compliance training session.</li>
<li>Avoid overexplaining basic finance terms to finance students, but do not assume non-finance students know filing form codes.</li>
</ul>
</section>
<section id="required-output" class="level2">
<h2 class="anchored" data-anchor-id="required-output">Required output</h2>
<p>Create the following deliverables:</p>
<ol type="1">
<li><code>corporate-filings.qmd</code>
<ul>
<li>Quarto revealJS source.</li>
<li>Should render cleanly with default revealJS settings or the user’s website default theme.</li>
<li>Do not over-style.</li>
<li>Use callouts, columns, fragments, simple diagrams, and charts.</li>
</ul></li>
<li><code>assets/</code>
<ul>
<li>Local images and charts.</li>
<li>Charts should be generated from embedded source data where possible.</li>
<li>Avoid remote image dependencies.</li>
</ul></li>
<li><code>README.md</code>
<ul>
<li><p>Include render instructions:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render corporate-filings.qmd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>Include required packages if using Python chunks.</p></li>
<li><p>Include notes about optional dependencies.</p></li>
</ul></li>
<li>Optional:
<ul>
<li><code>references.bib</code>, if using formal citations.</li>
<li><code>assets/chart_data.csv</code>, if easier for reproducibility.</li>
</ul></li>
</ol>
</section>
<section id="quarto-implementation-requirements" class="level2">
<h2 class="anchored" data-anchor-id="quarto-implementation-requirements">Quarto implementation requirements</h2>
<p>Use Quarto revealJS.</p>
<p>Suggested YAML:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span><span class="kw">:</span><span class="at"> </span><span class="st">"Corporate Filings as a Research Data Source"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">subtitle</span><span class="kw">:</span><span class="at"> </span><span class="st">"From research ideas to EDGAR, SeekEdgar, and information extraction"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">author</span><span class="kw">:</span><span class="at"> </span><span class="st">"Adrian Gao"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">date</span><span class="kw">:</span><span class="at"> today</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">format</span><span class="kw">:</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">revealjs</span><span class="kw">:</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">slide-number</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">chalkboard</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">preview-links</span><span class="kw">:</span><span class="at"> auto</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">incremental</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">code-overflow</span><span class="kw">:</span><span class="at"> wrap</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">html-math-method</span><span class="kw">:</span><span class="at"> katex</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">execute</span><span class="kw">:</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">echo</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">warning</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">message</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Avoid heavy custom CSS unless needed. The user’s website already enables default theming.</p>
<p>Use revealJS features:</p>
<ul>
<li>Section divider slides.</li>
<li>Columns.</li>
<li>Fragments for staged points.</li>
<li>Callouts:
<ul>
<li><code>callout-note</code> for key concepts.</li>
<li><code>callout-tip</code> for practical advice.</li>
<li><code>callout-warning</code> for pitfalls.</li>
<li><code>callout-important</code> for takeaways.</li>
</ul></li>
<li>Small code blocks only in the practical section or appendix.</li>
<li>Speaker notes are optional but useful.</li>
</ul>
<p>Do not use long walls of text. For a seminar deck, many slides should have one strong message and one visual.</p>
</section>
<section id="content-philosophy" class="level2">
<h2 class="anchored" data-anchor-id="content-philosophy">Content philosophy</h2>
<p>The talk should not be a catalog of filing codes.</p>
<p>The deck should repeatedly connect:</p>
<blockquote class="blockquote">
<p><strong>Research question → filing type → information extracted → empirical design</strong></p>
</blockquote>
<p>For example:</p>
<blockquote class="blockquote">
<p>Do lenders shape acquirer behavior? → loan agreement exhibits → acquisition covenants and collateral clauses → original contract-level dataset linked to M&amp;A outcomes.</p>
</blockquote>
<p>This framing is more useful than saying “Form 10-K contains Item 1, Item 1A, Item 7, etc.”</p>
</section>
<section id="overall-narrative" class="level2">
<h2 class="anchored" data-anchor-id="overall-narrative">Overall narrative</h2>
<p>The talk should follow this arc:</p>
<ol type="1">
<li><strong>Hook</strong>: Corporate filings are a public research infrastructure.</li>
<li><strong>Map</strong>: What the filing ecosystem contains.</li>
<li><strong>Examples</strong>: What kinds of research ideas filings enable.</li>
<li><strong>Workflow</strong>: How to move from idea to data.</li>
<li><strong>Tools</strong>: EDGAR, SEC APIs, SeekEdgar, Python.</li>
<li><strong>Pitfalls</strong>: How not to misuse filings.</li>
<li><strong>Activation</strong>: How students can start this month.</li>
</ol>
<p>The central message:</p>
<blockquote class="blockquote">
<p>Corporate filings are not just a finance dataset. They are a public, legally consequential, time-stamped archive of firm behavior.</p>
</blockquote>
</section>
<section id="timing-target" class="level2">
<h2 class="anchored" data-anchor-id="timing-target">Timing target</h2>
<p>Total: 40 minutes.</p>
<p>Suggested timing:</p>
<table class="table">
<thead>
<tr class="header">
<th>Section</th>
<th style="text-align: right;">Time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Opening and motivation</td>
<td style="text-align: right;">5 minutes</td>
</tr>
<tr class="even">
<td>Filing ecosystem</td>
<td style="text-align: right;">8 minutes</td>
</tr>
<tr class="odd">
<td>Research examples</td>
<td style="text-align: right;">12 minutes</td>
</tr>
<tr class="even">
<td>Workflow and tools</td>
<td style="text-align: right;">10 minutes</td>
</tr>
<tr class="odd">
<td>Pitfalls and takeaway</td>
<td style="text-align: right;">5 minutes</td>
</tr>
</tbody>
</table>
<p>Target deck length:</p>
<ul>
<li>Main slides: 26 to 30.</li>
<li>Appendix slides: 8 to 12.</li>
<li>Total source slides can be 38 to 42, but only 26 to 30 should be main-track slides.</li>
</ul>
</section>
<section id="must-use-factual-anchors" class="level2">
<h2 class="anchored" data-anchor-id="must-use-factual-anchors">Must-use factual anchors</h2>
<p>Use these verified facts and sources.</p>
<section id="sec-access-and-apis" class="level3">
<h3 class="anchored" data-anchor-id="sec-access-and-apis">SEC access and APIs</h3>
<p>The SEC states that submissions by company and extracted XBRL data are available via RESTful APIs on <code>data.sec.gov</code>, with JSON formatted data.</p>
<p>Source: - SEC Developer Resources: https://www.sec.gov/about/developer-resources - SEC EDGAR APIs: https://www.sec.gov/search-filings/edgar-application-programming-interfaces - SEC accessing EDGAR data: https://www.sec.gov/search-filings/edgar-search-assistance/accessing-edgar-data</p>
</section>
<section id="edgar-full-text-search" class="level3">
<h3 class="anchored" data-anchor-id="edgar-full-text-search">EDGAR full-text search</h3>
<p>The SEC full-text search gives access to the full text of electronic filings submitted since 2001.</p>
<p>Source: - SEC EDGAR Full Text Search: https://www.sec.gov/edgar/search/ - SEC Full Text Search FAQ: https://www.sec.gov/edgar/search/efts-faq.html</p>
</section>
<section id="sec-filing-volume-and-search-volume" class="level3">
<h3 class="anchored" data-anchor-id="sec-filing-volume-and-search-volume">SEC filing volume and search volume</h3>
<p>Use this as a visually engaging statistic slide.</p>
<p>From the SEC FY 2025 Congressional Budget Justification, workload data for the EDGAR Business Office:</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">FY 2023 actual</th>
<th style="text-align: right;">FY 2024 estimate</th>
<th style="text-align: right;">FY 2025 request</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Online searches for EDGAR filings, in millions</td>
<td style="text-align: right;">21,730</td>
<td style="text-align: right;">22,817</td>
<td style="text-align: right;">23,957</td>
</tr>
<tr class="even">
<td>Number of electronic filings received, in millions</td>
<td style="text-align: right;">2.43</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">2.58</td>
</tr>
</tbody>
</table>
<p>Interpretation: - 21,730 million searches = 21.73 billion searches. - 23,957 million searches = 23.957 billion searches. - Electronic filings received are around 2.4 to 2.6 million per year in these figures.</p>
<p>Source: - SEC FY 2025 Congressional Budget Justification, EDGAR Business Office workload data, page 77 in the PDF: https://www.sec.gov/files/fy-2025-congressional-budget-justification.pdf</p>
</section>
<section id="seekedgar" class="level3">
<h3 class="anchored" data-anchor-id="seekedgar">SeekEdgar</h3>
<p>SeekEdgar describes tools for searching SEC and Indian company filings across full documents, tables, footnotes, MD&amp;A, SOX 404 reports, audit reports, and CD&amp;A. It also emphasizes no-coding search workflows and Excel output.</p>
<p>Sources: - SeekEdgar home: https://www.seekedgar.com/ - SeekEdgar user guide or related pages, if accessible: https://www.seekedgar.com/fraank.html</p>
</section>
<section id="presenters-old-website-note" class="level3">
<h3 class="anchored" data-anchor-id="presenters-old-website-note">Presenter’s old website note</h3>
<p>Use the old note as the “you can do this” anchor. It introduces textual analysis on SEC filings, including building a filing index, downloading filings, and extracting information.</p>
<p>Source: - https://mingze-gao.com/posts/textual-analysis-on-sec-filings/</p>
</section>
<section id="presenters-jcf-paper" class="level3">
<h3 class="anchored" data-anchor-id="presenters-jcf-paper">Presenter’s JCF paper</h3>
<p>Use this as a light case study. Do not turn the presentation into a full paper presentation.</p>
<p>Paper: - Gao, Mingze, Thanh Son Luong, and Buhui Qiu. 2026. “Real Estate Collateral, Lender Screening, and M&amp;A Performance.” Journal of Corporate Finance 98: 102962. - DOI: https://doi.org/10.1016/j.jcorpfin.2026.102962</p>
<p>Key message for this talk: - The study uses hand-collected loan agreements linked to M&amp;A deals. - It shows how contractual details in filings can support original data construction. - The empirical point is not the main focus of the talk. The main focus is that filings and exhibits can reveal contract terms that are otherwise difficult to observe.</p>
<p>Sources: - ScienceDirect: https://www.sciencedirect.com/science/article/pii/S0929119926000209 - Macquarie researcher page: https://researchers.mq.edu.au/en/publications/real-estate-collateral-lender-screening-and-mampa-performance/ - Presenter research page: https://mingze-gao.com/research/</p>
</section>
</section>
<section id="important-writing-constraints" class="level2">
<h2 class="anchored" data-anchor-id="important-writing-constraints">Important writing constraints</h2>
<ul>
<li>Do not use em dashes.</li>
<li>Use precise short sentences.</li>
<li>Avoid filler.</li>
<li>Avoid saying “filings are boring but useful.” Instead, show that they are rich.</li>
<li>Avoid calling EDGAR a “database of annual reports.” It is much broader.</li>
<li>Avoid overusing 10-K, 10-Q, 8-K, and 13F.</li>
<li>Use the term “corporate filings” broadly, but clarify that EDGAR is a U.S. SEC system.</li>
<li>When discussing SeekEdgar, do not oversell. Present it as an exploratory and no-code complement to EDGAR and Python.</li>
</ul>
</section>
<section id="visual-design-requirements" class="level2">
<h2 class="anchored" data-anchor-id="visual-design-requirements">Visual design requirements</h2>
<p>Make the deck engaging.</p>
<p>Required visual elements:</p>
<ol type="1">
<li><strong>Big-number slide</strong>
<ul>
<li>Use SEC workload data.</li>
<li>Show electronic filings received and EDGAR searches.</li>
<li>Recommended visual:
<ul>
<li>Left: line/bar chart of electronic filings received, FY 2023 to FY 2025.</li>
<li>Right: line/bar chart of EDGAR searches, FY 2023 to FY 2025.</li>
</ul></li>
<li>Keep charts simple and readable.</li>
</ul></li>
<li><strong>Filing ecosystem map</strong>
<ul>
<li>Use a 2D map or grouped cards.</li>
<li>Group by research use-case:
<ul>
<li>Periodic reporting</li>
<li>Event disclosure</li>
<li>Ownership and trading</li>
<li>Governance and shareholder process</li>
<li>Capital raising</li>
<li>Deals and restructuring</li>
<li>Exhibits and contracts</li>
</ul></li>
</ul></li>
<li><strong>Research idea matrix</strong>
<ul>
<li>Rows: disciplines.</li>
<li>Columns: filing objects.</li>
<li>Each cell gives one example.</li>
<li>Keep it visually compact.</li>
</ul></li>
<li><strong>From question to dataset workflow</strong>
<ul>
<li>Simple pipeline:
<ul>
<li>Research question</li>
<li>Filing family</li>
<li>Manual inspection</li>
<li>Extraction rule</li>
<li>Validation</li>
<li>Dataset</li>
<li>Empirical design</li>
</ul></li>
</ul></li>
<li><strong>Data layers diagram</strong>
<ul>
<li>Corporate filing as layered object:
<ul>
<li>Metadata</li>
<li>Form items</li>
<li>Tables</li>
<li>XBRL facts</li>
<li>Text narratives</li>
<li>Exhibits</li>
<li>Signatures and dates</li>
</ul></li>
</ul></li>
<li><strong>Loan-contract case-study graphic</strong>
<ul>
<li>Show a pipeline:
<ul>
<li>Loan agreement exhibit</li>
<li>Collateral and covenant clauses</li>
<li>Hand-collected variables</li>
<li>Link to M&amp;A outcomes</li>
</ul></li>
<li>Use this to show “filings enable original data construction.”</li>
</ul></li>
<li><strong>Extraction ladder</strong>
<ul>
<li>Manual coding</li>
<li>Keyword search</li>
<li>Regex or rule-based parsing</li>
<li>HTML parsing</li>
<li>XBRL extraction</li>
<li>NLP or LLM-assisted coding</li>
<li>Human validation</li>
</ul></li>
<li><strong>Pitfall grid</strong>
<ul>
<li>Common error on left.</li>
<li>How to avoid it on right.</li>
</ul></li>
</ol>
<p>Optional visual elements:</p>
<ul>
<li>Screenshot-like mockups of EDGAR search pages.</li>
<li>A mock search query box with “AI”, “cybersecurity”, “credit agreement”, “customer concentration”.</li>
<li>A filing lifecycle timeline.</li>
<li>A “hidden goldmine” diagram showing main filing versus exhibit attachments.</li>
</ul>
<p>Do not use stock-photo clutter. Prefer diagrams, charts, and well-designed text blocks.</p>
</section>
<section id="embedded-chart-data" class="level2">
<h2 class="anchored" data-anchor-id="embedded-chart-data">Embedded chart data</h2>
<p>Use the following data for the big-number charts.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>edgar_stats <span class="op">=</span> [</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"fiscal_year"</span>: <span class="st">"FY 2023"</span>, <span class="st">"electronic_filings_millions"</span>: <span class="fl">2.43</span>, <span class="st">"online_searches_billions"</span>: <span class="fl">21.730</span>},</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"fiscal_year"</span>: <span class="st">"FY 2024"</span>, <span class="st">"electronic_filings_millions"</span>: <span class="fl">2.50</span>, <span class="st">"online_searches_billions"</span>: <span class="fl">22.817</span>},</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"fiscal_year"</span>: <span class="st">"FY 2025"</span>, <span class="st">"electronic_filings_millions"</span>: <span class="fl">2.58</span>, <span class="st">"online_searches_billions"</span>: <span class="fl">23.957</span>},</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Chart instruction:</p>
<ul>
<li>Do not imply these are all corporate operating-company filings. They are SEC EDGAR workload data.</li>
<li>Label clearly:
<ul>
<li>“Electronic filings received, millions”</li>
<li>“Online searches for EDGAR filings, billions”</li>
</ul></li>
<li>Source note:
<ul>
<li>“Source: SEC FY 2025 Congressional Budget Justification, EDGAR Business Office workload data.”</li>
</ul></li>
</ul>
</section>
<section id="slide-by-slide-specification" class="level2">
<h2 class="anchored" data-anchor-id="slide-by-slide-specification">Slide-by-slide specification</h2>
<section id="slide-1.-title" class="level3">
<h3 class="anchored" data-anchor-id="slide-1.-title">Slide 1. Title</h3>
<p>Title: <strong>Corporate Filings as a Research Data Source</strong></p>
<p>Subtitle: <strong>From research ideas to EDGAR, SeekEdgar, and information extraction</strong></p>
<p>Visual: - Minimal seminar title slide. - Optional subtle background made from small filing-form labels: 10-K, DEF 14A, S-1, 13D, EX-10, 20-F, 6-K, Form 4.</p>
<p>Speaker message: - This is not a talk about memorizing form codes. - It is a talk about using public disclosures to study firms.</p>
</section>
<section id="slide-2.-opening-hook" class="level3">
<h3 class="anchored" data-anchor-id="slide-2.-opening-hook">Slide 2. Opening hook</h3>
<p>Title: <strong>A public archive of firm behavior</strong></p>
<p>Content: - Firms disclose strategy, risks, transactions, ownership, governance, contracts, and financials. - The disclosures are public, time-stamped, and legally consequential. - This makes filings a research infrastructure, not just a reporting requirement.</p>
<p>Visual: - Three-column framing: - What firms do - What firms disclose - What researchers can measure</p>
<p>Callout:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-important}</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>The key opportunity is not just reading filings. It is converting disclosure into research variables.</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="slide-3.-why-this-matters-beyond-finance-and-accounting" class="level3">
<h3 class="anchored" data-anchor-id="slide-3.-why-this-matters-beyond-finance-and-accounting">Slide 3. Why this matters beyond finance and accounting</h3>
<p>Title: <strong>Not only finance and accounting</strong></p>
<p>Content as cards: - Strategy: competitive positioning, restructuring, market entry. - Management: leadership, governance, incentives, organizational change. - Innovation and IS: AI, cybersecurity, data governance, digital transformation. - Marketing: customers, channels, product risk, brand incidents. - Entrepreneurship: IPOs, founder control, venture exits. - Political economy: regulation, sanctions, geopolitical exposure.</p>
<p>Visual: - Discipline cards or a matrix.</p>
<p>Speaker message: - A filing can be read as a legal document, a financial report, a strategy document, or a text corpus.</p>
</section>
<section id="slide-4.-big-numbers" class="level3">
<h3 class="anchored" data-anchor-id="slide-4.-big-numbers">Slide 4. Big numbers</h3>
<p>Title: <strong>EDGAR is used at massive scale</strong></p>
<p>Content: - Around 2.4 to 2.6 million electronic filings received annually in SEC FY 2023 to FY 2025 workload data. - Around 21.7 to 24.0 billion online searches for EDGAR filings in the same workload data.</p>
<p>Visual: - Two charts: - Electronic filings received, millions. - Online searches, billions.</p>
<p>Source note: - SEC FY 2025 Congressional Budget Justification, EDGAR Business Office workload data.</p>
<p>Design: - This should be an engaging statistics slide, not a table-only slide.</p>
</section>
<section id="slide-5.-what-makes-filings-distinctive" class="level3">
<h3 class="anchored" data-anchor-id="slide-5.-what-makes-filings-distinctive">Slide 5. What makes filings distinctive?</h3>
<p>Title: <strong>Why filings are special as research data</strong></p>
<p>Use four blocks:</p>
<ol type="1">
<li><strong>Public</strong>
<ul>
<li>No proprietary access required for core EDGAR data.</li>
</ul></li>
<li><strong>Time-stamped</strong>
<ul>
<li>Filing dates and event dates can be linked to outcomes.</li>
</ul></li>
<li><strong>Rich</strong>
<ul>
<li>Text, tables, XBRL, exhibits, signatures, metadata.</li>
</ul></li>
<li><strong>Legally consequential</strong>
<ul>
<li>Disclosures are made under regulatory obligations.</li>
</ul></li>
</ol>
<p>Callout:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Filings are imperfect, strategic, and sometimes boilerplate. But those features can themselves become research objects.</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="slide-6.-section-divider" class="level3">
<h3 class="anchored" data-anchor-id="slide-6.-section-divider">Slide 6. Section divider</h3>
<p>Title: <strong>1. The filing ecosystem</strong></p>
<p>Subtitle: <strong>Think in research use-cases, not form codes</strong></p>
<p>Visual: - Dark or simple section divider, depending on site theme.</p>
</section>
<section id="slide-7.-what-is-edgar" class="level3">
<h3 class="anchored" data-anchor-id="slide-7.-what-is-edgar">Slide 7. What is EDGAR?</h3>
<p>Title: <strong>EDGAR in one slide</strong></p>
<p>Content: - SEC’s Electronic Data Gathering, Analysis, and Retrieval system. - Primary electronic submission and public access system for SEC filings. - Includes company filings, individual ownership filings, fund filings, exhibits, and metadata. - Public access through web search, company pages, full-text search, and APIs.</p>
<p>Visual: - Simple ecosystem: - Filers - EDGAR - Public users - Researchers - Investors - Regulators</p>
<p>Source: - SEC submit-filings or accessing EDGAR data pages.</p>
</section>
<section id="slide-8.-the-filing-universe-grouped-by-research-use" class="level3">
<h3 class="anchored" data-anchor-id="slide-8.-the-filing-universe-grouped-by-research-use">Slide 8. The filing universe, grouped by research use</h3>
<p>Title: <strong>A map of the filing universe</strong></p>
<p>Visual: - Large grouped map with seven groups:</p>
<ol type="1">
<li>Periodic reporting
<ul>
<li>10-K, 10-Q, 20-F, 40-F</li>
</ul></li>
<li>Event disclosure
<ul>
<li>8-K, 6-K</li>
</ul></li>
<li>Ownership and trading
<ul>
<li>13D, 13G, 13F, Forms 3, 4, 5</li>
</ul></li>
<li>Governance and shareholder process
<ul>
<li>DEF 14A, DEFA14A, PRE 14A</li>
</ul></li>
<li>Capital raising and listing
<ul>
<li>S-1, F-1, S-3, prospectuses</li>
</ul></li>
<li>Deals and restructuring
<ul>
<li>S-4, merger proxy, tender-offer filings, bankruptcy-related disclosures</li>
</ul></li>
<li>Exhibits
<ul>
<li>EX-10 credit agreements, employment contracts, merger agreements, charters, bylaws</li>
</ul></li>
</ol>
<p>Speaker message: - The form is only the starting point. The research variable may be in a section, a table, or an exhibit.</p>
</section>
<section id="slide-9.-periodic-reports" class="level3">
<h3 class="anchored" data-anchor-id="slide-9.-periodic-reports">Slide 9. Periodic reports</h3>
<p>Title: <strong>Periodic reports: the recurring narrative of the firm</strong></p>
<p>Content: - Business description. - Risk factors. - MD&amp;A. - Financial statements and footnotes. - Segment and geographic discussion. - Controls, legal proceedings, and management certification.</p>
<p>Research examples: - Cybersecurity risk language. - AI adoption disclosure. - Customer concentration. - International exposure. - Climate and supply-chain risk. - Accounting estimates and footnotes.</p>
<p>Visual: - Filing page as layered object.</p>
</section>
<section id="slide-10.-event-driven-filings" class="level3">
<h3 class="anchored" data-anchor-id="slide-10.-event-driven-filings">Slide 10. Event-driven filings</h3>
<p>Title: <strong>Event filings: when something material happens</strong></p>
<p>Content: - 8-Ks can report material agreements, leadership changes, results, impairments, restatements, financing events, acquisitions, and more. - Event filings are useful for event-study designs and for constructing event samples. - For foreign private issuers, 6-Ks often transmit important information released abroad or to foreign exchanges.</p>
<p>Visual: - Timeline: - Event - Filing - Market reaction - Follow-up disclosure - Outcome</p>
</section>
<section id="slide-11.-ownership-trading-and-influence" class="level3">
<h3 class="anchored" data-anchor-id="slide-11.-ownership-trading-and-influence">Slide 11. Ownership, trading, and influence</h3>
<p>Title: <strong>Ownership and influence</strong></p>
<p>Content: - 13F: institutional holdings. - 13D and 13G: beneficial ownership, activism, large stakes. - Forms 3, 4, 5: insider holdings and transactions. - Useful for studying governance, monitoring, activism, informed trading, and investor networks.</p>
<p>Visual: - Ownership network graphic: - Institution - Insider - Activist - Firm - Governance outcome</p>
<p>Caution: - Make clear 13F has reporting thresholds and only covers certain managers and securities.</p>
</section>
<section id="slide-12.-governance-and-shareholder-process" class="level3">
<h3 class="anchored" data-anchor-id="slide-12.-governance-and-shareholder-process">Slide 12. Governance and shareholder process</h3>
<p>Title: <strong>Proxy filings: boards, pay, voting, and shareholder voice</strong></p>
<p>Content: - DEF 14A and related proxy filings. - Executive compensation. - Director background. - Board structure. - Shareholder proposals. - Say-on-pay votes. - Related-party transactions.</p>
<p>Research examples: - CEO incentives and risk-taking. - Board diversity and monitoring. - Shareholder proposals and ESG. - Governance responses to poor performance.</p>
<p>Visual: - Proxy statement as three data panels: - People - Pay - Votes</p>
</section>
<section id="slide-13.-issuance-listing-and-entrepreneurial-firms" class="level3">
<h3 class="anchored" data-anchor-id="slide-13.-issuance-listing-and-entrepreneurial-firms">Slide 13. Issuance, listing, and entrepreneurial firms</h3>
<p>Title: <strong>Registration statements: firms telling their story to investors</strong></p>
<p>Content: - S-1 and F-1 for IPOs and foreign issuers. - Prospectuses for offerings. - Useful for entrepreneurship, venture exits, founder control, risk narratives, capital raising, and business models. - Rich textual information appears before public trading history is available.</p>
<p>Visual: - IPO lifecycle: - Private firm - S-1/F-1 - Roadshow and pricing - Public firm - Post-IPO outcomes</p>
</section>
<section id="slide-14.-exhibits-are-the-hidden-goldmine" class="level3">
<h3 class="anchored" data-anchor-id="slide-14.-exhibits-are-the-hidden-goldmine">Slide 14. Exhibits are the hidden goldmine</h3>
<p>Title: <strong>Exhibits: where contracts live</strong></p>
<p>Content: - Many filings include exhibits. - Exhibits can contain: - Credit agreements. - Acquisition agreements. - Employment contracts. - Underwriting agreements. - Charters and bylaws. - Supply or customer agreements. - Exhibits often hold details not summarized in the main filing.</p>
<p>Visual: - Main filing page with a magnifying glass pointing to <code>EX-10.1 Credit Agreement</code>.</p>
<p>Callout:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-important}</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>For many research questions, the exhibit is the dataset.</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="slide-15.-section-divider" class="level3">
<h3 class="anchored" data-anchor-id="slide-15.-section-divider">Slide 15. Section divider</h3>
<p>Title: <strong>2. What research can filings enable?</strong></p>
<p>Subtitle: <strong>From disclosure to original variables</strong></p>
</section>
<section id="slide-16.-research-idea-matrix" class="level3">
<h3 class="anchored" data-anchor-id="slide-16.-research-idea-matrix">Slide 16. Research idea matrix</h3>
<p>Title: <strong>One archive, many research questions</strong></p>
<p>Visual: - Matrix with disciplines as rows and filing objects as columns. - Example cells:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Discipline</th>
<th>Filing object</th>
<th>Research idea</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Finance</td>
<td>EX-10 credit agreements</td>
<td>How contract terms shape investment decisions</td>
</tr>
<tr class="even">
<td>Accounting</td>
<td>10-K footnotes</td>
<td>How estimates and internal controls affect reporting quality</td>
</tr>
<tr class="odd">
<td>Management</td>
<td>DEF 14A</td>
<td>How leadership and board structure shape strategy</td>
</tr>
<tr class="even">
<td>IS</td>
<td>10-K risk factors</td>
<td>How firms disclose cyber and AI risk</td>
</tr>
<tr class="odd">
<td>Entrepreneurship</td>
<td>S-1/F-1</td>
<td>How founder control affects IPO outcomes</td>
</tr>
<tr class="even">
<td>Marketing</td>
<td>10-K business sections</td>
<td>How customer concentration or product risk affects firm value</td>
</tr>
<tr class="odd">
<td>IB</td>
<td>20-F/6-K</td>
<td>How foreign issuers disclose geopolitical and regulatory exposure</td>
</tr>
</tbody>
</table>
<p>Keep this slide visual. Do not overcrowd.</p>
</section>
<section id="slide-17.-case-study-loan-contracts-from-filings" class="level3">
<h3 class="anchored" data-anchor-id="slide-17.-case-study-loan-contracts-from-filings">Slide 17. Case study: loan contracts from filings</h3>
<p>Title: <strong>Case study: loan contracts as research data</strong></p>
<p>Content: - Question: Can collateral and lender screening shape M&amp;A outcomes? - Data challenge: Detailed contract terms are not usually in standard datasets. - Filing opportunity: Loan agreement exhibits disclose collateral, covenants, and restrictions. - Research design: Hand-collected loan agreements linked to M&amp;A deals.</p>
<p>Visual: - Pipeline: - SEC filing - Loan agreement exhibit - Collateral and covenant clauses - Hand-collected variables - M&amp;A outcomes</p>
<p>Source: - Gao, Luong, and Qiu, Journal of Corporate Finance, 2026.</p>
<p>Speaker message: - The lesson is not just about real estate collateral. - The lesson is that filings can reveal contractual mechanisms behind corporate decisions.</p>
</section>
<section id="slide-18.-what-the-loan-contract-example-teaches" class="level3">
<h3 class="anchored" data-anchor-id="slide-18.-what-the-loan-contract-example-teaches">Slide 18. What the loan-contract example teaches</h3>
<p>Title: <strong>The broader lesson from contract exhibits</strong></p>
<p>Content: - Filings can reveal mechanisms, not just outcomes. - Hand collection can still be high value when the variable is not in commercial databases. - Contracts can connect banking, law, governance, and corporate investment. - A good filing-based project often starts with a small manual pilot.</p>
<p>Visual: - Four cards: - Mechanisms - Measurement - Validation - Original data</p>
<p>Callout:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-tip}</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>A strong filing project often begins with reading 20 filings very carefully.</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="slide-19.-narrative-disclosures" class="level3">
<h3 class="anchored" data-anchor-id="slide-19.-narrative-disclosures">Slide 19. Narrative disclosures</h3>
<p>Title: <strong>Text is data, but not automatically good data</strong></p>
<p>Content: - Risk factors. - MD&amp;A. - Business descriptions. - Legal proceedings. - Footnotes. - Auditor language. - Sustainability or climate-related language. - AI, cybersecurity, privacy, supply chain, sanctions, and geopolitical risk.</p>
<p>Research use: - Measure exposure, attention, concern, complexity, strategic orientation, or response to regulation.</p>
<p>Caution: - Boilerplate language is not always noise. It may itself be strategic.</p>
<p>Visual: - Text snippets with highlighted words, but do not quote large copyrighted passages. - Use synthetic sample snippets if needed.</p>
</section>
<section id="slide-20.-governance-and-influence-examples" class="level3">
<h3 class="anchored" data-anchor-id="slide-20.-governance-and-influence-examples">Slide 20. Governance and influence examples</h3>
<p>Title: <strong>Governance, ownership, and influence</strong></p>
<p>Content: - Proxy statements: compensation, boards, votes. - 13D/G: activism and block ownership. - Form 4: insider transactions. - 13F: institutional portfolios.</p>
<p>Example research questions: - Do activist threats reshape disclosure? - Do insider trades precede strategic announcements? - Do institutional holders influence innovation or ESG strategy? - Does board structure affect AI/cyber risk governance?</p>
<p>Visual: - Influence chain: - Owners - Governance - Managerial incentives - Disclosure or corporate policy - Outcomes</p>
</section>
<section id="slide-21.-innovation-and-digital-transformation-examples" class="level3">
<h3 class="anchored" data-anchor-id="slide-21.-innovation-and-digital-transformation-examples">Slide 21. Innovation and digital transformation examples</h3>
<p>Title: <strong>Filings for studying innovation, AI, and cyber risk</strong></p>
<p>Content: - Firms discuss technology in business descriptions, risk factors, MD&amp;A, and sometimes 8-Ks. - Cybersecurity incident disclosure and risk disclosure can be linked to market outcomes, governance, customers, and regulation. - AI disclosure can be studied as adoption, hype, risk, capability, or strategic orientation.</p>
<p>Visual: - Conceptual map: - Technology shock - Disclosure - Governance response - Market or real outcome</p>
<p>Callout:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-warning}</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>Do not treat every mention of “AI” as adoption. Start with careful validation.</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="slide-22.-foreign-issuers-and-comparative-work" class="level3">
<h3 class="anchored" data-anchor-id="slide-22.-foreign-issuers-and-comparative-work">Slide 22. Foreign issuers and comparative work</h3>
<p>Title: <strong>Foreign issuers: beyond U.S. domestic firms</strong></p>
<p>Content: - 20-F annual reports and 6-K current reports. - Useful for comparative disclosure, international strategy, cross-listing, regulatory exposure, and geopolitical risk. - But comparability issues are nontrivial.</p>
<p>Visual: - World map silhouette or global firm icons. - Avoid overcomplicated details.</p>
</section>
<section id="slide-23.-section-divider" class="level3">
<h3 class="anchored" data-anchor-id="slide-23.-section-divider">Slide 23. Section divider</h3>
<p>Title: <strong>3. From idea to data</strong></p>
<p>Subtitle: <strong>The practical workflow</strong></p>
</section>
<section id="slide-24.-workflow-from-research-question-to-dataset" class="level3">
<h3 class="anchored" data-anchor-id="slide-24.-workflow-from-research-question-to-dataset">Slide 24. Workflow from research question to dataset</h3>
<p>Title: <strong>A practical workflow</strong></p>
<p>Visual: - Pipeline: 1. Define construct. 2. Identify filing family. 3. Manually inspect filings. 4. Write extraction protocol. 5. Pilot and validate. 6. Scale download. 7. Link to outcomes. 8. Document decisions.</p>
<p>Content: - Emphasize that manual inspection comes before large-scale scraping.</p>
<p>Callout:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-important}</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>Do not automate before you understand what the relevant disclosure actually looks like.</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="slide-25.-data-layers-inside-a-filing" class="level3">
<h3 class="anchored" data-anchor-id="slide-25.-data-layers-inside-a-filing">Slide 25. Data layers inside a filing</h3>
<p>Title: <strong>A filing is not one object</strong></p>
<p>Visual: - Layered stack: - Metadata: CIK, accession number, filing date, form type. - Sections: items, MD&amp;A, risk factors. - Tables: compensation, financials, ownership. - XBRL: structured accounting facts. - Text: narratives and footnotes. - Exhibits: contracts and attachments.</p>
<p>Content: - Different layers require different extraction methods.</p>
</section>
<section id="slide-26.-search-first-scale-later" class="level3">
<h3 class="anchored" data-anchor-id="slide-26.-search-first-scale-later">Slide 26. Search first, scale later</h3>
<p>Title: <strong>Search first, scale later</strong></p>
<p>Content: - Start with EDGAR company search and full-text search. - Search phrases that should reveal the mechanism. - Inspect false positives and false negatives. - Build a short protocol. - Only then scale.</p>
<p>Visual: - Search box mockups: - “credit agreement” - “acquisition covenant” - “artificial intelligence” - “cybersecurity incident” - “customer concentration” - “going concern”</p>
<p>Mention: - SEC full-text search covers electronic filings since 2001. - It can filter by date, company, person, category, and location.</p>
</section>
<section id="slide-27.-edgar-and-seekedgar" class="level3">
<h3 class="anchored" data-anchor-id="slide-27.-edgar-and-seekedgar">Slide 27. EDGAR and SeekEdgar</h3>
<p>Title: <strong>EDGAR and SeekEdgar play different roles</strong></p>
<p>Content as comparison table:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Tool</th>
<th>Best for</th>
<th>Limitation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>EDGAR web search</td>
<td>Official access, company browsing, full-text search</td>
<td>Manual exploration can be slow</td>
</tr>
<tr class="even">
<td>SEC APIs</td>
<td>Reproducible downloads, submissions metadata, XBRL facts</td>
<td>Requires coding and careful request handling</td>
</tr>
<tr class="odd">
<td>SeekEdgar</td>
<td>Fast exploratory search, no-code extraction, tables, footnotes, MD&amp;A</td>
<td>Availability and access depend on subscription or institutional access</td>
</tr>
<tr class="even">
<td>Python</td>
<td>Flexible, reproducible pipelines</td>
<td>Requires validation and maintenance</td>
</tr>
</tbody>
</table>
<p>Speaker message: - Use the tool that matches the stage of the project. - Exploration and production are different tasks.</p>
</section>
<section id="slide-28.-light-python-example" class="level3">
<h3 class="anchored" data-anchor-id="slide-28.-light-python-example">Slide 28. Light Python example</h3>
<p>Title: <strong>A minimal Python example: from CIK to filing metadata</strong></p>
<p>Content: - Show only a compact example. - Use Apple or Microsoft as a familiar example. - Fetch company submissions JSON. - Print recent form types and accession numbers.</p>
<p>Example code:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>headers <span class="op">=</span> {</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"User-Agent"</span>: <span class="st">"your-name your-email@example.com"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>cik <span class="op">=</span> <span class="st">"0000320193"</span>  <span class="co"># Apple Inc.</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="ss">f"https://data.sec.gov/submissions/CIK</span><span class="sc">{</span>cik<span class="sc">}</span><span class="ss">.json"</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> requests.get(url, headers<span class="op">=</span>headers, timeout<span class="op">=</span><span class="dv">30</span>).json()</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>recent <span class="op">=</span> pd.DataFrame(data[<span class="st">"filings"</span>][<span class="st">"recent"</span>])</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>recent[[<span class="st">"form"</span>, <span class="st">"filingDate"</span>, <span class="st">"accessionNumber"</span>, <span class="st">"primaryDocument"</span>]].head(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Important note: - Include a real User-Agent with contact information when making scripted SEC requests. - Keep this as an example only. Do not run live in the static deck unless rendering environment supports internet.</p>
<p>Visual: - Code on the left, output mock table on the right.</p>
</section>
<section id="slide-29.-extraction-ladder" class="level3">
<h3 class="anchored" data-anchor-id="slide-29.-extraction-ladder">Slide 29. Extraction ladder</h3>
<p>Title: <strong>Information extraction: choose the right level</strong></p>
<p>Visual: - Ladder from simple to complex:</p>
<ol type="1">
<li>Manual coding.</li>
<li>Keyword screening.</li>
<li>Regular expressions.</li>
<li>HTML parsing.</li>
<li>XBRL facts.</li>
<li>NLP classification.</li>
<li>LLM-assisted extraction.</li>
<li>Human validation.</li>
</ol>
<p>Content: - Higher complexity is not always better. - For many projects, a validated rule is better than a black-box model.</p>
</section>
<section id="slide-30.-validation-is-the-research-design" class="level3">
<h3 class="anchored" data-anchor-id="slide-30.-validation-is-the-research-design">Slide 30. Validation is the research design</h3>
<p>Title: <strong>Validation is not an afterthought</strong></p>
<p>Content: - Randomly check extracted observations. - Track false positives and false negatives. - Compare against hand-coded samples. - Record ambiguous cases. - Predefine coding rules where possible. - Report validation clearly.</p>
<p>Visual: - Confusion matrix or simple validation checklist.</p>
<p>Callout:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-warning}</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>The most common weakness in filing-based research is not access. It is unvalidated extraction.</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="slide-31.-section-divider" class="level3">
<h3 class="anchored" data-anchor-id="slide-31.-section-divider">Slide 31. Section divider</h3>
<p>Title: <strong>4. Common pitfalls</strong></p>
<p>Subtitle: <strong>Where filing-based projects fail</strong></p>
</section>
<section id="slide-32.-pitfall-grid" class="level3">
<h3 class="anchored" data-anchor-id="slide-32.-pitfall-grid">Slide 32. Pitfall grid</h3>
<p>Title: <strong>Common pitfalls and fixes</strong></p>
<p>Create a two-column grid:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Pitfall</th>
<th>Fix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treating form type as content</td>
<td>Inspect items, sections, and exhibits</td>
</tr>
<tr class="even">
<td>Confusing filing date and event date</td>
<td>Extract both and justify timing</td>
</tr>
<tr class="odd">
<td>Ignoring amendments</td>
<td>Track <code>/A</code> filings and restatements</td>
</tr>
<tr class="even">
<td>Ignoring exhibits</td>
<td>Search exhibit indexes</td>
</tr>
<tr class="odd">
<td>Overusing keywords</td>
<td>Validate semantic meaning</td>
</tr>
<tr class="even">
<td>Assuming text is comparable over time</td>
<td>Account for rule changes and templates</td>
</tr>
<tr class="odd">
<td>Not documenting parsing decisions</td>
<td>Build a reproducible protocol</td>
</tr>
<tr class="even">
<td>Letting LLMs extract without audit</td>
<td>Use human validation samples</td>
</tr>
</tbody>
</table>
</section>
<section id="slide-33.-ethical-and-practical-notes" class="level3">
<h3 class="anchored" data-anchor-id="slide-33.-ethical-and-practical-notes">Slide 33. Ethical and practical notes</h3>
<p>Title: <strong>Responsible use of public filings</strong></p>
<p>Content: - Public does not mean effortless. - Respect SEC access policies and rate limits. - Include contact details in scripted requests. - Avoid unnecessary repeated downloads. - Preserve reproducibility. - Do not infer sensitive individual-level claims beyond what the filing supports.</p>
<p>Visual: - Small checklist.</p>
</section>
<section id="slide-34.-how-to-start-this-month" class="level3">
<h3 class="anchored" data-anchor-id="slide-34.-how-to-start-this-month">Slide 34. How to start this month</h3>
<p>Title: <strong>A four-step starter plan</strong></p>
<p>Content: 1. Pick one construct you cannot easily observe in standard datasets. 2. Identify two or three likely filing families. 3. Read 20 filings manually. 4. Build a pilot extraction and validation table.</p>
<p>Callout:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-tip}</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>The goal of the first week is not a full dataset. It is to prove that the signal exists.</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="slide-35.-closing-takeaway" class="level3">
<h3 class="anchored" data-anchor-id="slide-35.-closing-takeaway">Slide 35. Closing takeaway</h3>
<p>Title: <strong>Corporate filings are research infrastructure</strong></p>
<p>Content: - They are public, longitudinal, and legally consequential. - They contain text, tables, XBRL, events, contracts, and metadata. - They can support both hand-collected and scalable computational research. - The best projects begin with a sharp construct and careful reading.</p>
<p>Final one-liner: &gt; Start with a research question, not a form code.</p>
<p>Visual: - Reuse the workflow pipeline, now simplified.</p>
</section>
</section>
<section id="appendix-slide-specifications" class="level2">
<h2 class="anchored" data-anchor-id="appendix-slide-specifications">Appendix slide specifications</h2>
<p>The appendix should be useful for technically inclined students but should not interrupt the main 40-minute flow.</p>
<section id="appendix-a1.-links-and-resources" class="level3">
<h3 class="anchored" data-anchor-id="appendix-a1.-links-and-resources">Appendix A1. Links and resources</h3>
<p>Include: - SEC EDGAR search: https://www.sec.gov/edgar/search/ - SEC company search: https://www.sec.gov/edgar/browse/ - SEC developer resources: https://www.sec.gov/about/developer-resources - SEC EDGAR APIs: https://www.sec.gov/search-filings/edgar-application-programming-interfaces - SEC accessing EDGAR data: https://www.sec.gov/search-filings/edgar-search-assistance/accessing-edgar-data - Presenter’s note: https://mingze-gao.com/posts/textual-analysis-on-sec-filings/ - SeekEdgar: https://www.seekedgar.com/</p>
</section>
<section id="appendix-a2.-common-filing-families" class="level3">
<h3 class="anchored" data-anchor-id="appendix-a2.-common-filing-families">Appendix A2. Common filing families</h3>
<p>Use a compact table:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Family</th>
<th>Examples</th>
<th>Typical research use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Periodic reports</td>
<td>10-K, 10-Q, 20-F, 40-F</td>
<td>Business, risks, financials, MD&amp;A</td>
</tr>
<tr class="even">
<td>Current reports</td>
<td>8-K, 6-K</td>
<td>Events, agreements, management changes</td>
</tr>
<tr class="odd">
<td>Ownership</td>
<td>13D, 13G, 13F, Forms 3/4/5</td>
<td>Ownership, activism, insider trading</td>
</tr>
<tr class="even">
<td>Proxy</td>
<td>DEF 14A, PRE 14A</td>
<td>Boards, pay, votes, proposals</td>
</tr>
<tr class="odd">
<td>Registration</td>
<td>S-1, F-1, S-3</td>
<td>IPOs, offerings, firm narratives</td>
</tr>
<tr class="even">
<td>Deals</td>
<td>S-4, merger proxy, tender offers</td>
<td>M&amp;A, restructuring, control changes</td>
</tr>
<tr class="odd">
<td>Exhibits</td>
<td>EX-10, EX-2, EX-3</td>
<td>Contracts, charters, material agreements</td>
</tr>
</tbody>
</table>
</section>
<section id="appendix-a3.-sec-api-endpoints" class="level3">
<h3 class="anchored" data-anchor-id="appendix-a3.-sec-api-endpoints">Appendix A3. SEC API endpoints</h3>
<p>List with examples:</p>
<ul>
<li>Company submissions:
<ul>
<li><code>https://data.sec.gov/submissions/CIK##########.json</code></li>
</ul></li>
<li>Company facts:
<ul>
<li><code>https://data.sec.gov/api/xbrl/companyfacts/CIK##########.json</code></li>
</ul></li>
<li>Company concept:
<ul>
<li><code>https://data.sec.gov/api/xbrl/companyconcept/CIK##########/us-gaap/AccountsPayableCurrent.json</code></li>
</ul></li>
<li>Frames:
<ul>
<li><code>https://data.sec.gov/api/xbrl/frames/us-gaap/AccountsPayableCurrent/USD/CY2019Q1I.json</code></li>
</ul></li>
</ul>
<p>Mention: - CIK must be zero padded to 10 digits. - Use a proper User-Agent.</p>
</section>
<section id="appendix-a4.-python-example-list-recent-filings" class="level3">
<h3 class="anchored" data-anchor-id="appendix-a4.-python-example-list-recent-filings">Appendix A4. Python example: list recent filings</h3>
<p>Use the code from Slide 28, but include more explanation.</p>
</section>
<section id="appendix-a5.-python-example-construct-a-filing-url" class="level3">
<h3 class="anchored" data-anchor-id="appendix-a5.-python-example-construct-a-filing-url">Appendix A5. Python example: construct a filing URL</h3>
<p>Show how accession numbers are converted into archive paths.</p>
<p>Example:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>cik_int <span class="op">=</span> <span class="st">"320193"</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>accession <span class="op">=</span> <span class="st">"0000320193-24-000123"</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>accession_no_dash <span class="op">=</span> accession.replace(<span class="st">"-"</span>, <span class="st">""</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>archive_base <span class="op">=</span> <span class="ss">f"https://www.sec.gov/Archives/edgar/data/</span><span class="sc">{</span><span class="bu">int</span>(cik_int)<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>accession_no_dash<span class="sc">}</span><span class="ss">/"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(archive_base)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Caution: - The primary document filename comes from the submissions JSON. - Do not hard-code filenames unless verified.</p>
</section>
<section id="appendix-a6.-from-search-terms-to-validation-table" class="level3">
<h3 class="anchored" data-anchor-id="appendix-a6.-from-search-terms-to-validation-table">Appendix A6. From search terms to validation table</h3>
<p>Show a sample validation protocol:</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Definition</th>
<th>Source</th>
<th>Extraction rule</th>
<th>Validation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AI disclosure</td>
<td>Firm discusses AI as capability or strategy</td>
<td>10-K Item 1, Item 7</td>
<td>keyword screen plus manual coding</td>
<td>100 random filings</td>
</tr>
<tr class="even">
<td>Cyber incident</td>
<td>Material cybersecurity event</td>
<td>8-K</td>
<td>item-based and keyword screen</td>
<td>all positives manually checked</td>
</tr>
<tr class="odd">
<td>Credit agreement</td>
<td>Loan contract disclosed</td>
<td>EX-10</td>
<td>exhibit description contains credit agreement</td>
<td>sample checked against exhibit index</td>
</tr>
<tr class="even">
<td>Acquisition covenant</td>
<td>Clause restricting acquisitions</td>
<td>loan agreement exhibit</td>
<td>clause extraction</td>
<td>dual-coded subset</td>
</tr>
</tbody>
</table>
</section>
<section id="appendix-a7.-seekedgar-workflow" class="level3">
<h3 class="anchored" data-anchor-id="appendix-a7.-seekedgar-workflow">Appendix A7. SeekEdgar workflow</h3>
<p>Describe conceptual workflow:</p>
<ol type="1">
<li>Search phrase.</li>
<li>Limit filing type or section.</li>
<li>Inspect snippets and tables.</li>
<li>Export results.</li>
<li>Validate manually.</li>
<li>Use for pilot or to design programmatic extraction.</li>
</ol>
<p>Do not include screenshots unless available and permitted.</p>
</section>
<section id="appendix-a8.-good-research-question-templates" class="level3">
<h3 class="anchored" data-anchor-id="appendix-a8.-good-research-question-templates">Appendix A8. Good research question templates</h3>
<p>Examples:</p>
<ul>
<li>What disclosure reveals a mechanism not available in standard datasets?</li>
<li>What firm behavior is documented before market outcomes are observed?</li>
<li>What contract term or governance mechanism shapes future decisions?</li>
<li>What regulatory change altered how firms disclose a topic?</li>
<li>What text can distinguish substantive adoption from symbolic disclosure?</li>
</ul>
</section>
<section id="appendix-a9.-suggested-readings" class="level3">
<h3 class="anchored" data-anchor-id="appendix-a9.-suggested-readings">Appendix A9. Suggested readings</h3>
<p>Include: - Presenter’s old note. - Gao, Luong, and Qiu, 2026, Journal of Corporate Finance. - A few classic or representative SEC textual analysis papers, if the producer knows them and can cite accurately. - Do not invent citations. If uncertain, omit.</p>
</section>
</section>
<section id="python-chart-generation-guidance" class="level2">
<h2 class="anchored" data-anchor-id="python-chart-generation-guidance">Python chart generation guidance</h2>
<p>If generating charts in Quarto with Python, use simple <code>matplotlib</code> or <code>pandas</code> plots. Do not over-style.</p>
<p>Example chunk:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>stats <span class="op">=</span> pd.DataFrame([</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"FY"</span>: <span class="st">"FY 2023"</span>, <span class="st">"Electronic filings received"</span>: <span class="fl">2.43</span>, <span class="st">"Online searches"</span>: <span class="fl">21.730</span>},</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"FY"</span>: <span class="st">"FY 2024"</span>, <span class="st">"Electronic filings received"</span>: <span class="fl">2.50</span>, <span class="st">"Online searches"</span>: <span class="fl">22.817</span>},</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"FY"</span>: <span class="st">"FY 2025"</span>, <span class="st">"Electronic filings received"</span>: <span class="fl">2.58</span>, <span class="st">"Online searches"</span>: <span class="fl">23.957</span>},</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>ax.bar(stats[<span class="st">"FY"</span>], stats[<span class="st">"Electronic filings received"</span>])</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Millions"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Electronic filings received"</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>ax.spines[[<span class="st">"top"</span>, <span class="st">"right"</span>]].set_visible(<span class="va">False</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>If using one chart per slide, ensure text remains large enough for a seminar room.</p>
</section>
<section id="suggested-design-patterns-in-quarto" class="level2">
<h2 class="anchored" data-anchor-id="suggested-design-patterns-in-quarto">Suggested design patterns in Quarto</h2>
<section id="columns" class="level3">
<h3 class="anchored" data-anchor-id="columns">Columns</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>:::: {.columns}</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>::: {.column width="50%"}</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>Main idea here.</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>::: {.column width="50%"}</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="al">![](assets/chart.png)</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>::::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="callouts" class="level3">
<h3 class="anchored" data-anchor-id="callouts">Callouts</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-tip}</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>A strong filing-based project often begins by reading 20 filings very carefully.</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="fragments" class="level3">
<h3 class="anchored" data-anchor-id="fragments">Fragments</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>::: {.fragment}</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>The hard part is not finding filings.</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>::: {.fragment}</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>The hard part is knowing what in the filing maps to your construct.</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="section-divider" class="level3">
<h3 class="anchored" data-anchor-id="section-divider">Section divider</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># 1. The filing ecosystem</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>or</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. The filing ecosystem {.center}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>depending on theme behavior.</p>
</section>
</section>
<section id="style-and-pacing-rules" class="level2">
<h2 class="anchored" data-anchor-id="style-and-pacing-rules">Style and pacing rules</h2>
<ol type="1">
<li>Most slides should have one key message.</li>
<li>No slide should contain more than 6 bullets unless it is a compact appendix table.</li>
<li>Use examples frequently.</li>
<li>Use form codes only after explaining the research use.</li>
<li>Avoid dense legal text.</li>
<li>Use “research idea” callouts.</li>
<li>Use charts and diagrams to keep visual interest.</li>
<li>Do not make the first 10 minutes technical.</li>
<li>Keep Python to one main slide plus appendix.</li>
<li>Use the loan-contract case study to showcase possibility, not to present the full paper.</li>
</ol>
</section>
<section id="suggested-research-idea-callouts" class="level2">
<h2 class="anchored" data-anchor-id="suggested-research-idea-callouts">Suggested “research idea” callouts</h2>
<p>Sprinkle 4 to 6 of these across the deck.</p>
<p>Example:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title="Research idea"}</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>Do firms that disclose AI as a strategic capability make different workforce, acquisition, or cybersecurity investments?</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title="Research idea"}</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>Can contract exhibits reveal how lenders constrain future acquisitions, payouts, or asset sales?</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title="Research idea"}</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>Do firms change risk-factor language after competitors experience cyber incidents?</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title="Research idea"}</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>Can IPO registration statements reveal whether founder control changes post-IPO strategy?</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="specific-instructions-for-the-loan-contract-case-study" class="level2">
<h2 class="anchored" data-anchor-id="specific-instructions-for-the-loan-contract-case-study">Specific instructions for the loan-contract case study</h2>
<p>Use two slides only in the main deck.</p>
<p>Do not overdo finance details.</p>
<p>Slide 1 should introduce the case:</p>
<ul>
<li>Public filings can disclose loan agreements as exhibits.</li>
<li>Those agreements contain contractual terms.</li>
<li>The paper hand-collects loan agreements linked to M&amp;A deals.</li>
<li>This enables study of collateral, covenants, lender screening, and acquisition outcomes.</li>
</ul>
<p>Slide 2 should extract the general lesson:</p>
<ul>
<li>Filings enable original variable construction.</li>
<li>Contracts reveal mechanisms.</li>
<li>Manual data collection can be valuable when commercial datasets do not contain the key variable.</li>
<li>Start small, validate carefully, then scale.</li>
</ul>
<p>Use citation: - Gao, Luong, and Qiu, 2026, Journal of Corporate Finance, DOI: 10.1016/j.jcorpfin.2026.102962.</p>
</section>
<section id="specific-instructions-for-seekedgar" class="level2">
<h2 class="anchored" data-anchor-id="specific-instructions-for-seekedgar">Specific instructions for SeekEdgar</h2>
<p>Do not frame SeekEdgar as replacing EDGAR.</p>
<p>Frame as:</p>
<ul>
<li>Useful for exploratory search.</li>
<li>Helpful for no-code users.</li>
<li>Useful for searching text, sections, footnotes, tables, MD&amp;A, SOX reports, audit reports, CD&amp;A, and similar filing components.</li>
<li>Useful for generating pilot evidence and candidate samples.</li>
<li>For final published research, still validate and document extraction carefully.</li>
</ul>
<p>Avoid claims about exact coverage unless verified from current SeekEdgar pages.</p>
</section>
<section id="specific-instructions-for-edgar-api" class="level2">
<h2 class="anchored" data-anchor-id="specific-instructions-for-edgar-api">Specific instructions for EDGAR API</h2>
<p>Keep the API section light.</p>
<p>Use these messages:</p>
<ul>
<li>SEC APIs can give reproducible access to company submissions and XBRL facts.</li>
<li>APIs are best for metadata and structured data.</li>
<li>Full-text and exhibit-level extraction still requires additional parsing.</li>
<li>Always use a proper User-Agent.</li>
<li>Do not aggressively scrape.</li>
</ul>
<p>Do not teach a full scraping framework in the main deck.</p>
</section>
<section id="quality-checklist-before-delivery" class="level2">
<h2 class="anchored" data-anchor-id="quality-checklist-before-delivery">Quality checklist before delivery</h2>
<p>The deck should pass these checks:</p>
<section id="content-checks" class="level3">
<h3 class="anchored" data-anchor-id="content-checks">Content checks</h3>
<ul>
<li>Does it go beyond 10-K, 10-Q, 8-K, and 13F?</li>
<li>Does it explain exhibits clearly?</li>
<li>Does it include the JCF loan-contract example?</li>
<li>Does it include EDGAR, SEC APIs, and SeekEdgar?</li>
<li>Does it include Python, but not too much?</li>
<li>Does it include practical pitfalls?</li>
<li>Does it include research examples across disciplines?</li>
<li>Does it include the presenter’s old note as a resource?</li>
</ul>
</section>
<section id="visual-checks" class="level3">
<h3 class="anchored" data-anchor-id="visual-checks">Visual checks</h3>
<ul>
<li>Are there at least five non-text visual slides?</li>
<li>Is there a big-number chart slide?</li>
<li>Is there a filing universe map?</li>
<li>Is there a workflow diagram?</li>
<li>Is there a case-study pipeline?</li>
<li>Is there a pitfall grid?</li>
</ul>
</section>
<section id="pedagogical-checks" class="level3">
<h3 class="anchored" data-anchor-id="pedagogical-checks">Pedagogical checks</h3>
<ul>
<li>Would a non-finance student understand why filings matter?</li>
<li>Would a finance student still learn something new?</li>
<li>Does the deck inspire research ideas?</li>
<li>Does the deck avoid becoming a compliance or legal taxonomy lecture?</li>
<li>Does it lower the activation barrier?</li>
</ul>
</section>
<section id="technical-checks" class="level3">
<h3 class="anchored" data-anchor-id="technical-checks">Technical checks</h3>
<ul>
<li>Does <code>quarto render corporate-filings.qmd</code> work?</li>
<li>Are all assets local?</li>
<li>Are external links in an appendix?</li>
<li>Are Python chunks optional or renderable without live internet?</li>
<li>Are code blocks readable on slides?</li>
<li>Are source notes included where factual statistics are shown?</li>
</ul>
</section>
</section>
<section id="suggested-final-slide-wording" class="level2">
<h2 class="anchored" data-anchor-id="suggested-final-slide-wording">Suggested final slide wording</h2>
<p>Title: <strong>Start with a research question, not a form code</strong></p>
<p>Content: - What do firms do that is hard to observe? - Which disclosure would reveal it? - Can you validate the signal in 20 filings? - Can you scale it responsibly?</p>
<p>Final line: &gt; Corporate filings are not just documents to read. They are empirical traces of firm behavior.</p>
</section>
<section id="final-instruction-to-the-deck-producer" class="level2">
<h2 class="anchored" data-anchor-id="final-instruction-to-the-deck-producer">Final instruction to the deck producer</h2>
<p>Build a polished static Quarto revealJS deck that a finance academic can deliver to mixed business school research students in 40 minutes. The deck must feel like a research seminar, not a software tutorial. It should be engaging, visual, and practically useful. The most important outcome is that students leave with a broader understanding of what corporate filings contain and a concrete sense that they can use filings to build novel research variables.</p>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mingze-gao\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><a href="https://www.mq.edu.au/research/research-centres-groups-and-facilities/centres/fintech-and-banking"><img src="../../..\images/MQ_FABRC_HOR_RGB_REV.png" class="light-content" alt="MQ FinTech and Banking Research Centre" height="67"></a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Copyright © 2019 - 2026 Mingze Gao
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mgao6767">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/AdrianMingzeGao">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/adriangao/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:mingze.gao@mq.edu.au">
      <i class="bi bi-send" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>