---
title: "AFIN8003 Week 10 - Liability and Liquidity Management"
subtitle: "Banking and Financial Intermediation"
author: "Dr. Mingze Gao"
institute: "Department of Applied Finance"
date: 2024-10-09
draft: true
categories:
    - AFIN8003
    - 2024S2
format: 
  mq-revealjs: 
    chalkboard: true
    embed-resources: false
    echo: true
    code-fold: true
    footer: "AFIN8003 Banking and Financial Intermediation"
    mermaid-format: svg
  pdf:
    echo: false
    documentclass: article
    papersize: a4
    toc: true
    number-sections: true
    colorlinks: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fig-pos: "H"
    fig-width: 1
    fig-cap-location: "bottom"
    output-file: "Week10.pdf"
# Custom fields
pdf-name: "Week10.pdf"
---

# Liability and Liquidity Management

## Introduction

- [Last week](https://mingze-gao.com/teaching/AFIN8003/2024S2/Week9/) we discussed the __liquidity risk__ of financial institutions (FIs), especially depositary institutions (DIs).
- We understand that liquidity risk can arise from both asset side and liability side.
- DIs can insulate their balance sheets from liquidity risk by efficiently managing their liquid asset positions or managing the liability structure of their portfolios.
- Most DI managers incorporate both asset management and liability management as part of overall liquidity management strategy.
- This week, we discuss the various liquid assets and liabilities a DI might use to manage liquidity risk, and the risk–return trade-off associated with various liability and liquidity strategies employed. 

## Source of liquidity

Historically, primary method of meeting cash demands: _asset liquidity_ (stored liquidity)

- Examples: cash, treasury securities, certificates of deposits

Today, primary method of meeting cash demands: _liability liquidity_ / management (purchased liquidity)

- Examples: interbank market for exchange settled funds, repos, interbank market

Stock of liquid assets in an FI depends on

- FI's willingness to trade off liquidity and returns
- FI's ability to use liability liquidity

Non-traditional ways of obtaining liquidity include

- securitisation
- use of repurchase agreement markets
- use of capital markets

# Asset-side liquidity and management

## Liquid asset management

- Liquid assets are traded in a _deep_ market
    - Even large trading volumes will not impact on price
    - Liquid assets include Treasury notes and Treasury bonds
- Liquid securities carry a comparatively lower interest rate: risk–return trade-off
- Low levels of liquidity expose an FI to greater illiquidity and withdrawal run risk
- Liquidity requirements are set to lessen the following risks
    - run on a bank
    - monetary policy
    - taxation implications
        - reserve requirement tax: the cost of holding reserves when the central bank pays no—or below market—interest on these balances

## Composition of the liquidity asset portfolio

- The composition of an FI’s liquid asset portfolio, especially with respect to cash and government securities, is partly determined by:
    - earnings consideration
    - minimum liquid-asset reserve requirements imposed by the central bank
- Historically, many countries had imposed reserve ratios[^reserve-ratio]
- Government securities act as secondary reserves (buffer reserves)
    - In times of a liquidity crisis, when significant drains on cash reserves occur, these securities can be turned into cash quickly and with very little loss of principal value because of the deep nature of the markets in which these assets are traded.

[^reserve-ratio]: See last week's note.

## Risk-return trade-off for liquid assets

- Managing the securities portfolio is an integral part of liquidity management for financial institutions
- The conflict between and the balance of the risk of illiquidity and the desire to maintain a high investment return is at the heart of management of the liquid asset portfolio
    - Trade off the benefits and costs of holding liquid assets
      - Cash immediacy versus reduced return
- The determinants of an FI's optimal liquid asset ratio depend on a number of factors:
    1. The variability of deposit inflows and outflows
    2. The yield on non-liquid assets.
    3. The liquidation costs of highly non-liquid assets.
    4. Higher interest rates paid on purchased funds/liabilities in the short-term money market, or in utilising the RBA liquidity facilities, will increase the desired liquidity asset/cash ratio

::: {.content-hidden when-format="pdf"}
## Risk-return trade-off for liquid assets (cont'd)
:::

- Day-to-day liquidity management means that a DI faces the risk of either undershooting or overshooting the required liquidity requirement on any given day.
    - Undershooting the regulatory required liquidity ratios (e.g., LCR, NSFR) may involve specified additional charges—penalties for not complying with regulations.
    - The cost of overshooting or holding cash reserves in excess of the minimum required, depends on whether the DI perceives its prudent level of reserves to meet expected and unexpected deposit withdrawals to be higher or lower than its regulatory requirement.[^cost-of-esa]
- The management of a DI’s __exchange settlement account (ESA)__ at the RBA is critical.

[^cost-of-esa]: RBA pays ['cash target rate minus 10 basis points'](https://www.rba.gov.au/education/resources/explainers/how-rba-implements-monetary-policy.html#:~:text=The%20Reserve%20Bank%20currently%20pays%20an%20interest%20rate%20on%20ES%20balances%20that%20is%200.1%20percentage%20points%20below%20the%20cash%20rate%20target.) interest on ESA balances.

::: {.callout-note}
ESA is an account held at the Reserve Bank of Australia by financial institutions to settle financial obligations arising from the clearing of payments.
:::

## The cash market and Exchange Settlement Account (ESA)

The __cash market__ is where banks lend and borrow funds from each other, typically on an overnight basis. These funds can be used to:

- **Meet liquidity needs**: Banks may borrow funds to ensure they meet short-term liquidity requirements, such as the ESA balances.
- Support lending activities: Banks may also use borrowed funds to support ongoing lending activities.
- Facilitate settlement of transactions: The funds can help banks settle large-scale interbank transactions efficiently.
- ......

Importantly,

- The _price_ of funds in this market is the interest rate on these interbank loans, which is called the __cash rate__ in Australia.
- The _quantity_ traded in this market is called the Exchange Settlement (ES) balance - the balance of DI's deposit accounts at the RBA, the ESA.

## The cash market, ESA, and repo transactions

RBA sets a target for the cash rate, it is often referred to as a "tool" of monetary policy.

Prior to the COVID-19 recession,

- the cash rate target was the RBA's only active monetary policy tool.
- the RBA managed the supply of ES balances so that it met estimated demand and the cash rate was close to its target.
- the RBA achieved cash rate target through open market operations, particularly through __repurchase agreements (repos)__.

::: {.callout-note title="Repo transactions of RBA"}
A repo is a transaction with two parts. 

- In the first part, the Reserve Bank could lend ES balances to a bank and receive a bond in exchange. This increases the supply of ES balances available to banks. 
- In the pre-arranged second part, the transaction is reversed. The Reserve Bank returns the bond and receives back the ES balances, which decreases the supply of ES balances.
:::

After the introduction of the package of policy measures in response to the COVID-19 recession,

- ES balances substantially increased.
- the RBA, as a result, no longer conducts daily open market operations to manage ES balances.

## Repo transactions to manage liquidity (ES balance)

- Two sources of exchange settlement liquidity for Australian DIs provided by RBA repos
    - Intra-day repo: a facility that allows a DI to utilise RBA repos to obtain intra-day liquidity, with the repo reversed later in the same day
    - Overnight repo: a facility that allows a DI to use RBA repos in order to obtain liquidity overnight to fund its liquidity settlement needs
- After introduction of same day settlement, RBA also introduced open RBA repo.
    - Open RBA repo: an RBA repurchase agreement with no specified end date
- With Basel III reforms, starting on 1 January 2015, the committed liquidity facility is also introduced.
    - Committed liquidity facility: a facility providing secured line of credit from the central bank allowed under Basel III in regimes which do not have sufficient liquid assets to meet the Basel III liquidity reforms

## The changing dynamics

Since COVID-19, the RBA significantly adjusted its monetary operations, moving away from repos as the primary tool for managing liquidity. Banks now manage their ESA balances primarily through other mechanisms:

- Term Funding Facility (TFF): Introduced during the pandemic, the TFF allowed banks to access longer-term funding at very low rates. It helped banks manage funding needs over the pandemic period.
- Standing Facility: Banks can still access liquidity via the RBA’s standing liquidity facility, where they can borrow overnight at a penalty rate if their ESA balances fall short.
- Interbank Cash Market: Banks continue to borrow and lend among themselves in the interbank cash market to manage daily fluctuations in their ESA balances.
- Repo Transactions in the Private Market. While the RBA no longer conducts open market repos, banks and other financial institutions still use repo transactions with each other as a way to manage liquidity and secure short-term funding. These private market repos are similar in structure to the RBA's past operations but are conducted bilaterally between financial institutions.
- Liquidity Management via Government Bond Purchases: The RBA engaged in large-scale government bond purchases to inject liquidity into the financial system. This action increased the level of reserves in the banking system, reducing the immediate need for repo operations. Banks manage their liquidity more through excess reserves than through the previous need for constant repo transactions.

# Liability-side liquidity and management

## Liability management

- Close link to liquidity management
- Overall aim of liability management: to construct a low-cost, low–withdrawal risk liability portfolio
- Problems
    - Low-cost liabilities often carry high withdrawal risk: demand deposits
    - Low withdrawal risk often comes with high cost: certificates of deposit (CDs)

::: {.content-hidden when-format="pdf"}
## Liability management (cont'd)
:::

Deposit liabilities

- Cheque account and other demand deposits
- Savings account
- Cash management account / investment savings accounts
- Fixed-term deposits
- Negotiable certificates of deposits (NCDs)

Non-deposit liabilities

- Interbank funds
- Repurchase agreements (Repos)
- Covered bonds
- Other borrowings
- Bank accepted bills
- Commercial bills or non-bank bills
- Commercial paper or promissory notes
- Subordinated debt, medium-term notes and long-term borrowings

## Choice of liability structure: deposits

- Current deposits or other at-call funds
- High degree of withdrawal risk
- Low cost
    - Can recapture costs by charging fee such as cost per cheque cleared or electronic transaction.

$$
\text{Average implicit interest rate (IIR)} = \frac{\text{DI's average management cost per account – average fees earned per account}}{\text{average annual size of account}}
$$

## Choice of liability structure: interest-bearing cheque accounts

- Lower degree of withdrawal risk compared to current accounts
    - Minimum balance requirements
- Comparably higher cost: three pricing mechanisms
    - Implicit interest payments
    - Minimum balance requirements
    - Explicit interest payments
- Gross interest return = explicit interest + implicit interest

## Choice of liability structure: savings account

## Choice of liability structure: investment savings account

## Choice of liability structure: term of fixed-term deposits

## Choice of liability structure: negotiable certificates of deposits (NCDs)

## Choice of liability structure: non-deposit liabilities

## Liquidity regulation

# Finally...

## Suggested readings

- [How RBA implements monetary policy](https://www.rba.gov.au/education/resources/explainers/how-rba-implements-monetary-policy.html).
- [RBA Exchange Settlement Account Policy](https://www.rba.gov.au/payments-and-infrastructure/esa/).
- [RBA Standing Facilities](https://www.rba.gov.au/mkt-operations/resources/tech-notes/standing-facilities.html).

## References
