---
title: "AFIN8003 - Workshop 11"
subtitle: "Banking and Financial Intermediation"
author: "Dr. Mingze Gao"
institute: "Department of Applied Finance"
date: 2024-10-16
categories:
    - AFIN8003
    - 2024S2
format: 
  pdf:
    documentclass: article
    papersize: a4
    toc: false
    number-sections: true
    colorlinks: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fig-pos: "H"
    fig-width: 1
    fig-cap-location: "bottom"
    output-file: "Workshop11.pdf"
# Custom fields
pdf-name: "Workshop11.pdf"
include-answers: false
---

# MCQ

1. The risk that a borrower may not be able to make payments on a contractual obligation because of interference by an outside governmentalparty is:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] interest rate risk
   - [ ] operating risk
   - [ ] foreign exchange risk
   - [ ] sovereign risk 
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] interest rate risk
   - [ ] operating risk
   - [ ] foreign exchange risk
   - [x] sovereign risk 
   :::

1. The outright cancellation of all current and future foreign debt and equity obligations is called:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] a Brady bond
   - [ ] a MYRA
   - [ ] a debt moratorium
   - [ ] a debt repudiation
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] a Brady bond
   - [ ] a MYRA
   - [ ] a debt moratorium
   - [x] a debt repudiation
   :::

1. Which of the following internal evaluation models relies on the production of goods as well as the price of such goods?

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] the investment ratio
   - [ ] the domestic money supply growth
   - [ ] the import ratio
   - [ ] variance of export revenue
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] the investment ratio
   - [ ] the domestic money supply growth
   - [x] the import ratio
   - [ ] variance of export revenue
   :::

1. The following will lead to a higher probability of debt restructuring for a country:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] a negative relationship with the debt servicing ratio.
   - [ ] a negative relationship with the import ratio.
   - [ ] a lower level of sovereign debt.
   - [ ] a positive relationship with both the debt service ratio and the import ratio.
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] a negative relationship with the debt servicing ratio.
   - [ ] a negative relationship with the import ratio.
   - [ ] a lower level of sovereign debt.
   - [x] a positive relationship with both the debt service ratio and the import ratio.
   :::

1. A lender (FI) may benefit from debt restructuring in the following way:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] the FI cannot benefit.
   - [ ] the restructuring may mean the loan becomes similar to a long-term bond.
   - [ ] less regulatory attention.
   - [ ] a restructuring is better than a loan default.
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] the FI cannot benefit.
   - [ ] the restructuring may mean the loan becomes similar to a long-term bond.
   - [ ] less regulatory attention.
   - [x] a restructuring is better than a loan default.
   :::

1. The market in which foreign currency is traded for immediate delivery is the:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] spot market
   - [ ] futures market
   - [ ] forward market
   - [ ] London market
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [x] spot market
   - [ ] futures market
   - [ ] forward market
   - [ ] London market
   :::

1. An FI has $100 in FX assets and $80 in FX liabilities. The FI also has $60 in FX currency purchased and $90 in FX currency sold. The net FXexposure is:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] $20
   - [ ] -$30
   - [ ] $10
   - [ ] -$10
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] $20
   - [ ] -$30
   - [ ] $10
   - [x] -$10
   :::

1. An unhedged position in a particular foreign currency is:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] an open position
   - [ ] a short position
   - [ ] a long position
   - [ ] facing the risk of loss if the exchange rate moves in either direction
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [x] an open position
   - [ ] a short position
   - [ ] a long position
   - [ ] facing the risk of loss if the exchange rate moves in either direction
   :::

1. Off-balance-sheet activities have:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] risk-reducing attributes
   - [ ] risk-increasing attributes
   - [ ] profit-enhancing characteristics
   - [ ] All of the listed options are correct.
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] risk-reducing attributes
   - [ ] risk-increasing attributes
   - [ ] profit-enhancing characteristics
   - [x] All of the listed options are correct.
   :::

1. Items that affect the future, rather than the current, shape of an FI's balance sheet are:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] contingent assets
   - [ ] contingent liabilities
   - [ ] off-balance-sheet items
   - [ ] All of the listed options are correct.
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] contingent assets
   - [ ] contingent liabilities
   - [ ] off-balance-sheet items
   - [x] All of the listed options are correct.
   :::

1. Loan commitments are examples of:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] contingent assets
   - [ ] contingent liabilities
   - [ ] off-balance-sheet liabilities
   - [ ] All of the listed options are correct.
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [x] contingent assets
   - [ ] contingent liabilities
   - [ ] off-balance-sheet liabilities
   - [ ] All of the listed options are correct.
   :::

1. A contingent contract that guarantees the trade performance of the buyer of the guaranty is a:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] standby letter of credit
   - [ ] commercial (documentary) letter of credit
   - [ ] forward contract
   - [ ] loan commitment
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] standby letter of credit
   - [x] commercial (documentary) letter of credit
   - [ ] forward contract
   - [ ] loan commitment
   :::

1. A back-end fee or commitment fee is:

   ::: {.content-hidden when-meta="include-answers"}
   - [ ] a fee charged upfront for a loan
   - [ ] a fee charged by the borrower to the FI
   - [ ] a fee the FI charges the borrower for any unused balances in the commitment line
   - [ ] a fee charged at the back end of a loan
   :::
   ::: {.content-hidden unless-meta="include-answers"}
   - [ ] a fee charged upfront for a loan
   - [ ] a fee charged by the borrower to the FI
   - [x] a fee the FI charges the borrower for any unused balances in the commitment line
   - [ ] a fee charged at the back end of a loan
   :::

# Short answer questions

## Q1

An FI has issued a one-year loan commitment of $2 million for an upfront fee of 25 basis points. The back-end fee on the unused portion of the commitment is 10 basis points. The FI requires a compensating balance of 5 per cent as demand deposits. The FI’s cost of funds is 6 percent, the interest rate on the loan is 10 per cent, and reserve requirements on demand deposits are 8 per cent. The customer is expected to draw down 80 per cent of the commitment at the beginning of the year.

(a) What is the expected return on the loan without taking future values into consideration?
(b) What is the expected return using future values? That is, the net fee and interest income are evaluated at the end of the year when the loan is due.
(c) How is the expected return in part (b) affected if the reserve requirements on demand deposits are zero?
(d) How is the expected return in part (b) affected if compensating balances are paid a nominal interest rate of 5 per cent?
(e) What is the expected return using future values but with the compensating balance placed in certificates of deposit that have an interest rate of 5.5 per cent and no reserve requirements, rather than in demand deposits?

::: {.content-hidden unless-meta="include-answers"}
::: {.callout-tip title="Example answer"}
(a)
     Income:

     - Upfront fees = $0.0025 \times \$2 000 000 = \$5 000$
     - Interest income = $0.10 \times \$2 000 000(.80) = \$160 000$
     - Back-end fee = $0.0010 \times \$2 000 000(1 – 0.80) = \$400$
     - Total = \$165 400

     Funds committed:

     - Funds drawn down = $2 000 000(0.80)
     - Compensating balances = $\$2 000 000 \times 0.80 \times 0.05 = \$80000$
     - Reserve requirements on demand deposits = $\$80 000 \times 0.08 = \$6400$
     - Total = $2 000 000(0.80) – $80 000 + $6400 = $1 526 400

     Expected return = $\$165 400/\$1 526 400 = 10.836\%$

     Alternatively, use the formula

     $$
     \begin{aligned}
     1+k &= 1+ \frac{f_1+f_2(1-td) + (BR+\phi) td}{td - b\times td (1-RR)} \\
         &= 1+ \frac{0.0025+0.0010(1-0.8) + 0.1\times 0.8}{0.8 - 0.05\times 0.8 (1-0.08)} \\
         &= 1.10836
     \end{aligned}
     $$

(b)
     The only difference is that the upfront fee is estimated at year-end, that is, $5000 × 1.06 = $5300. Thus, expected return = $165 700/$1 526400 = 10.8556 per cent.

     Using the formula:

     1+k = 1 + [0.0025(1 + 0.06) + 0.0010(1 – 0.80) + 0.10(0.80)]/{0.80 – [0.05(0.80)(1 – 0.08)]}
     => 1+k = 1.108556, or k = 10.8556 per cent.

(c)
     In this case, the amount of funds committed is reduced by the amount normally set for reserves, that is, $6400. Thus, expected return = $165 700/$1 520 000 = 10.90 per cent.

     Using the formula:

     1 + k = 1 + [0.0025(1 + .06) + 0.0010(1 – 0.80) + 0.10(0.80)]/ {0.80 – [0.05(0.80)]}
     1 + k = 1.1090, or k = 10.90 per cent.

(d)
     Here, we need to subtract additional payments of interest on reserve requirements from the total fees and interest earned, that is, 0.05 × $80000 = $4000.  Expected return = $161 700/1 526 400 = 10.5936 per cent

     Using the formula:

     1 + k =1+[0.0025(1+ 0.06) + 0.0010(1 – 0.80) + 0.10(0.80) – 0.05(0.05)(0.80)]/[0.80 – 0.05(0.80)(1 – 0.08)]
     1 + k = 1.105936, or k = 10.5936 per cent.

(e)
     In this case we assume that the compensating balance is placed in certificates of deposits paying 5.5 per cent and with no compensating balance requirement. Thus, revenue in part (b) above is reduced by $80 000 × 0.055 = $4400, and the expected return is $161 300/$1 520000 = 10.612 per cent.

     Using the formula:

     1 + k = 1 + [0.0025(1 + 0.06) + 0.0010(1 – 0.80) + 0.10(0.80) – (0.05)(0.8)(0.055)]/{0.80 – [0.05(0.80)]}
     => 1 + k = 1.10612, or k = 10.612 per cent.
:::
:::

## Q2

A corporation is planning to issue $1 million of 270-day commercial paper for an effective yield of 5 per cent. The corporation expects to save 30 basis points on the interest rate by using either an SLC or a loan commitment as collateral for the issue.

(a) What are the net savings to the corporation if a bank agrees to provide a 270-day SLC for an upfront fee of 20 basis points (of the face value of the loan commitment) to back the commercial paper issue?
(b) What are the net savings to the corporation if a bank agrees to provide a 270-day loan commitment to back the issue? The bank will charge 10 basis points for an upfront fee and 10 basis points for a back-end fee for any unused portion of the loan. Assume the loan is not needed and that the fees are on the face value of the loan commitment.
(c) Should the corporation be indifferent to the two alternative collateral methods at the time the commercial paper is issued?

::: {.content-hidden unless-meta="include-answers"}
::: {.callout-tip title="Example answer"}
(a)
     - Cost of using SLC = – (0.0020) × $1 000 000 = –$2000.00
     - Savings by using SLC as collateral = (0.0030 × 270)/365 × $1 000 000 = $2219.18
     - Net savings = $219.18

(b)
     - Upfront fee of loan commitment = – (0.0010) × $1 000 000 = –$1000.00
     - Back-end fee (assuming no usage) = – (0.0010) × $1 000 000 = –$1000.00
     - Cost of loan commitment = –$2000.00
     - Savings by using loan commitments as collateral = (0.0030 × 270)/365 × $1 000 000 = $2219.18
     - Net savings = $219.18

(c)
     Not necessarily. If some of the loan commitment is drawn down, the back-end fee will be less and the savings will be greater.

:::
:::